-- Tow & Trade: depozyt + akceptacja udziału w licytacji

alter table public.market_vehicles
  add column if not exists auction_deposit_amount integer not null default 5000,
  add column if not exists auction_bank_account text;

create table if not exists public.market_auction_registrations (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.market_vehicles(id) on delete cascade,
  bidder_name text not null,
  bidder_phone text,
  bidder_token uuid not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid,
  unique(vehicle_id, bidder_token)
);

create index if not exists market_auction_registrations_vehicle_idx on public.market_auction_registrations(vehicle_id, created_at desc);
create index if not exists market_auction_registrations_status_idx on public.market_auction_registrations(status);

alter table public.market_auction_registrations enable row level security;

drop policy if exists "auction registrations staff read" on public.market_auction_registrations;
create policy "auction registrations staff read"
on public.market_auction_registrations for select
to authenticated using (true);

drop policy if exists "auction registrations staff update" on public.market_auction_registrations;
create policy "auction registrations staff update"
on public.market_auction_registrations for update
to authenticated using (true) with check (true);

grant select, update on public.market_auction_registrations to authenticated;

create or replace function public.request_market_auction_access(
  p_vehicle_id bigint,
  p_bidder_name text,
  p_bidder_phone text,
  p_bidder_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v public.market_vehicles%rowtype;
  r public.market_auction_registrations%rowtype;
begin
  if length(trim(coalesce(p_bidder_name,''))) < 2 then
    raise exception 'Podaj imię i nazwisko.';
  end if;

  select * into v from public.market_vehicles where id = p_vehicle_id;
  if not found or v.sale_mode <> 'auction' then
    raise exception 'Ta licytacja nie istnieje.';
  end if;
  if v.status <> 'available' or v.auction_ends_at is null or v.auction_ends_at <= now() then
    raise exception 'Ta licytacja nie przyjmuje już zgłoszeń.';
  end if;

  insert into public.market_auction_registrations(vehicle_id,bidder_name,bidder_phone,bidder_token,status)
  values (p_vehicle_id,trim(p_bidder_name),nullif(trim(coalesce(p_bidder_phone,'')),''),p_bidder_token,'pending')
  on conflict (vehicle_id,bidder_token) do update
    set bidder_name = excluded.bidder_name,
        bidder_phone = excluded.bidder_phone,
        status = case when public.market_auction_registrations.status='approved' then 'approved' else 'pending' end
  returning * into r;

  return jsonb_build_object(
    'ok', true,
    'status', r.status,
    'auction_number', lpad(v.id::text,4,'0'),
    'deposit_amount', coalesce(v.auction_deposit_amount,5000),
    'bank_account', coalesce(v.auction_bank_account,''),
    'bidder_name', r.bidder_name
  );
end;
$$;

create or replace function public.get_market_auction_access(
  p_vehicle_id bigint,
  p_bidder_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v public.market_vehicles%rowtype;
  r public.market_auction_registrations%rowtype;
begin
  select * into v from public.market_vehicles where id=p_vehicle_id;
  if not found then return jsonb_build_object('exists',false); end if;

  select * into r from public.market_auction_registrations
  where vehicle_id=p_vehicle_id and bidder_token=p_bidder_token;

  if not found then
    return jsonb_build_object(
      'exists',false,
      'auction_number',lpad(v.id::text,4,'0'),
      'deposit_amount',coalesce(v.auction_deposit_amount,5000),
      'bank_account',coalesce(v.auction_bank_account,'')
    );
  end if;

  return jsonb_build_object(
    'exists',true,
    'status',r.status,
    'bidder_name',r.bidder_name,
    'auction_number',lpad(v.id::text,4,'0'),
    'deposit_amount',coalesce(v.auction_deposit_amount,5000),
    'bank_account',coalesce(v.auction_bank_account,'')
  );
end;
$$;

create or replace function public.place_market_bid_verified(
  p_vehicle_id bigint,
  p_bidder_token uuid,
  p_amount integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v public.market_vehicles%rowtype;
  r public.market_auction_registrations%rowtype;
  v_min integer;
begin
  select * into r from public.market_auction_registrations
  where vehicle_id=p_vehicle_id and bidder_token=p_bidder_token and status='approved';
  if not found then raise exception 'Najpierw musisz zostać zaakceptowany do tej licytacji.'; end if;

  select * into v from public.market_vehicles where id=p_vehicle_id for update;
  if not found or v.sale_mode <> 'auction' then raise exception 'Ta licytacja nie istnieje.'; end if;
  if v.status <> 'available' or v.auction_ends_at is null or v.auction_ends_at <= now() then raise exception 'Licytacja jest zakończona.'; end if;

  v_min := coalesce(v.auction_current_bid,v.auction_start_price,0) + greatest(coalesce(v.auction_min_increment,500),1);
  if p_amount < v_min then raise exception 'Minimalna kolejna oferta to $%.',v_min; end if;

  insert into public.market_auction_bids(vehicle_id,bidder_name,bidder_phone,amount)
  values (p_vehicle_id,r.bidder_name,coalesce(r.bidder_phone,''),p_amount);

  update public.market_vehicles
  set auction_current_bid=p_amount,
      auction_bid_count=coalesce(auction_bid_count,0)+1,
      updated_at=now()
  where id=p_vehicle_id;

  return jsonb_build_object(
    'ok',true,
    'current_bid',p_amount,
    'bid_count',coalesce(v.auction_bid_count,0)+1,
    'next_minimum',p_amount+greatest(coalesce(v.auction_min_increment,500),1)
  );
end;
$$;

revoke all on function public.request_market_auction_access(bigint,text,text,uuid) from public;
revoke all on function public.get_market_auction_access(bigint,uuid) from public;
revoke all on function public.place_market_bid_verified(bigint,uuid,integer) from public;

grant execute on function public.request_market_auction_access(bigint,text,text,uuid) to anon, authenticated;
grant execute on function public.get_market_auction_access(bigint,uuid) to anon, authenticated;
grant execute on function public.place_market_bid_verified(bigint,uuid,integer) to anon, authenticated;
