-- StreetScope -> Supabase -> FiveM -> LB Phone
-- Before running: replace CHANGE_ME_QUEUE_SECRET with a long random secret.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.phone_notifications (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('article','fashion','motor','guide')),
  entity_id bigint not null,
  app text not null default 'streetscope',
  title text not null,
  content text,
  thumbnail text,
  url text,
  status text not null default 'pending' check (status in ('pending','processing','sent','failed')),
  attempts integer not null default 0,
  created_by text,
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  sent_at timestamptz,
  next_attempt_at timestamptz not null default now(),
  last_error text
);

create index if not exists phone_notifications_queue_idx
  on public.phone_notifications (status, next_attempt_at, created_at);

alter table public.phone_notifications enable row level security;
revoke all on table public.phone_notifications from anon, authenticated;

create table if not exists public.phone_notification_settings (
  id smallint primary key default 1 check (id = 1),
  queue_secret_hash text not null,
  updated_at timestamptz not null default now()
);

alter table public.phone_notification_settings enable row level security;
revoke all on table public.phone_notification_settings from anon, authenticated;

insert into public.phone_notification_settings (id, queue_secret_hash, updated_at)
values (1, encode(extensions.digest('CHANGE_ME_QUEUE_SECRET', 'sha256'), 'hex'), now())
on conflict (id) do update
set queue_secret_hash = excluded.queue_secret_hash,
    updated_at = now();

create or replace function public.claim_phone_notifications(
  p_secret text,
  p_limit integer default 10
)
returns table (
  id bigint,
  app text,
  title text,
  content text,
  thumbnail text,
  url text,
  kind text,
  entity_id bigint,
  attempts integer
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not exists (
    select 1
    from public.phone_notification_settings s
    where s.id = 1
      and s.queue_secret_hash = encode(extensions.digest(coalesce(p_secret, ''), 'sha256'), 'hex')
  ) then
    raise exception 'unauthorized';
  end if;

  return query
  with picked as (
    select n.id
    from public.phone_notifications n
    where (
      (n.status = 'pending' and n.next_attempt_at <= now())
      or (n.status = 'processing' and n.claimed_at < now() - interval '2 minutes')
    )
      and n.attempts < 5
    order by n.created_at asc
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 10), 25))
  ), updated as (
    update public.phone_notifications n
    set status = 'processing',
        claimed_at = now(),
        attempts = n.attempts + 1,
        last_error = null
    from picked
    where n.id = picked.id
    returning n.id, n.app, n.title, n.content, n.thumbnail, n.url, n.kind, n.entity_id, n.attempts
  )
  select u.id, u.app, u.title, u.content, u.thumbnail, u.url, u.kind, u.entity_id, u.attempts
  from updated u;
end;
$$;

create or replace function public.finish_phone_notification(
  p_secret text,
  p_id bigint,
  p_success boolean,
  p_error text default null
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_attempts integer;
begin
  if not exists (
    select 1
    from public.phone_notification_settings s
    where s.id = 1
      and s.queue_secret_hash = encode(extensions.digest(coalesce(p_secret, ''), 'sha256'), 'hex')
  ) then
    raise exception 'unauthorized';
  end if;

  select n.attempts into v_attempts
  from public.phone_notifications n
  where n.id = p_id
  for update;

  if not found then
    return false;
  end if;

  if p_success then
    update public.phone_notifications
    set status = 'sent',
        sent_at = now(),
        claimed_at = null,
        last_error = null
    where id = p_id;
  elsif v_attempts >= 5 then
    update public.phone_notifications
    set status = 'failed',
        claimed_at = null,
        last_error = left(coalesce(p_error, 'Unknown LB Phone error'), 1000)
    where id = p_id;
  else
    update public.phone_notifications
    set status = 'pending',
        claimed_at = null,
        next_attempt_at = now() + make_interval(secs => least(60, 15 * greatest(1, v_attempts))),
        last_error = left(coalesce(p_error, 'Unknown LB Phone error'), 1000)
    where id = p_id;
  end if;

  return true;
end;
$$;

revoke all on function public.claim_phone_notifications(text, integer) from public;
revoke all on function public.finish_phone_notification(text, bigint, boolean, text) from public;
grant execute on function public.claim_phone_notifications(text, integer) to anon;
grant execute on function public.finish_phone_notification(text, bigint, boolean, text) to anon;
