"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabase } from "../../lib/supabase";
import "./market.css";

type Vehicle={id:number;brand:string;model:string;year:number|null;price:number;mileage:number|null;image_url:string|null;status:string;featured:boolean;drivetrain:string|null;transmission:string|null;sale_mode:"sale"|"auction";auction_start_price:number|null;auction_min_increment:number|null;auction_current_bid:number|null;auction_bid_count:number|null;auction_ends_at:string|null};

export default function MarketPage(){
 const [rows,setRows]=useState<Vehicle[]>([]);const [q,setQ]=useState("");const [status,setStatus]=useState("available");const [mode,setMode]=useState("all");
 useEffect(()=>{(async()=>{const {data}=await getSupabase().from("market_vehicles").select("id,brand,model,year,price,mileage,image_url,status,featured,drivetrain,transmission,sale_mode,auction_start_price,auction_min_increment,auction_current_bid,auction_bid_count,auction_ends_at").order("featured",{ascending:false}).order("created_at",{ascending:false});setRows((data as Vehicle[]|null)??[]);})()},[]);
 const filtered=useMemo(()=>rows.filter(v=>(status==="all"||v.status===status)&&(mode==="all"||v.sale_mode===mode)&&`${v.brand} ${v.model}`.toLowerCase().includes(q.toLowerCase())),[rows,q,status,mode]);
 return <main className="market"><header className="market-nav"><a href="/" className="market-logo">STREET<span>SCOPE</span></a><nav><a href="/">GŁÓWNA</a><a href="/motor">MOTOR</a><a className="active" href="/market">TOW & TRADE</a></nav></header><section className="market-hero"><p>STREETSCOPE × TOW & TRADE</p><h1>TOW &<br/><em>TRADE.</em></h1><span>Samochody dostępne w salonie i licytacje prowadzone przez Tow & Trade.</span></section><section className="market-tools"><input placeholder="SZUKAJ MARKI / MODELU" value={q} onChange={e=>setQ(e.target.value)}/><select value={mode} onChange={e=>setMode(e.target.value)}><option value="all">WSZYSTKIE OFERTY</option><option value="sale">SPRZEDAŻ</option><option value="auction">LICYTACJE</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="available">AKTYWNE</option><option value="reserved">ZAREZERWOWANE</option><option value="sold">SPRZEDANE</option><option value="all">WSZYSTKIE STATUSY</option></select></section><section className="market-grid">{filtered.map(v=>{const ended=v.sale_mode==="auction"&&v.auction_ends_at&&new Date(v.auction_ends_at)<=new Date();const displayPrice=v.sale_mode==="auction"?(v.auction_current_bid??v.auction_start_price??0):v.price;return <a className={`vehicle-card ${v.status} ${v.sale_mode==="auction"?"auction-card":""}`} href={`/market/${v.id}`} key={v.id}><div className="vehicle-photo" style={v.image_url?{backgroundImage:`url(${v.image_url})`}:undefined}>{v.featured&&<b>WYRÓŻNIONE</b>}<span>{v.sale_mode==="auction"?(ended?"LICYTACJA ZAKOŃCZONA":"LICYTACJA"):v.status==="sold"?"SPRZEDANE":v.status==="reserved"?"ZAREZERWOWANE":"NA SPRZEDAŻ"}</span></div><div className="vehicle-info"><small>{v.year||"—"}{v.mileage!=null?` · ${v.mileage.toLocaleString("pl-PL")} MI`:""}</small><h2>{v.brand} {v.model}</h2><p>{v.sale_mode==="auction"?`${v.auction_bid_count||0} ofert · podbicie min. $${Number(v.auction_min_increment||500).toLocaleString("en-US")}`:[v.drivetrain,v.transmission].filter(Boolean).join(" · ")||"TOW & TRADE"}</p><strong>{v.sale_mode==="auction"?(v.auction_current_bid?"AKTUALNA OFERTA":"CENA STARTOWA"):"CENA"} · ${Number(displayPrice||0).toLocaleString("en-US")}</strong>{v.sale_mode==="auction"&&v.auction_ends_at&&!ended&&<small className="auction-end">KONIEC: {new Date(v.auction_ends_at).toLocaleString("pl-PL")}</small>}</div></a>})}{filtered.length===0&&<div className="market-empty">BRAK OFERT PASUJĄCYCH DO FILTRÓW.</div>}</section><footer className="market-footer"><b>TOW & TRADE</b><span>We współpracy ze StreetScope.</span></footer></main>;
}