"use client";

import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { getSupabase } from "../../../lib/supabase";
import "../market.css";

type Vehicle={id:number;brand:string;model:string;year:number|null;price:number;mileage:number|null;drivetrain:string|null;transmission:string|null;engine:string|null;color:string|null;description:string|null;image_url:string|null;gallery:string[]|null;seller_name:string|null;seller_phone:string|null;status:string;sale_mode:"sale"|"auction";auction_start_price:number|null;auction_min_increment:number|null;auction_current_bid:number|null;auction_bid_count:number|null;auction_ends_at:string|null};

export default function MarketVehiclePage(){
 const params=useParams<{id:string}>();const [v,setV]=useState<Vehicle|null>(null);const [loading,setLoading]=useState(true);const [bidderName,setBidderName]=useState("");const [bidderPhone,setBidderPhone]=useState("");const [bidAmount,setBidAmount]=useState("");const [bidMessage,setBidMessage]=useState("");const [bidBusy,setBidBusy]=useState(false);
 const load=async()=>{const {data}=await getSupabase().from("market_vehicles").select("*").eq("id",Number(params.id)).maybeSingle();const row=(data as Vehicle|null)??null;setV(row);if(row?.sale_mode==="auction"){const next=(row.auction_current_bid??row.auction_start_price??0)+(row.auction_min_increment||500);setBidAmount(String(next))}setLoading(false)};
 useEffect(()=>{load()},[params.id]);
 const placeBid=async(e:FormEvent)=>{e.preventDefault();if(!v)return;setBidBusy(true);setBidMessage("");try{const amount=Number(bidAmount);const {data,error}=await getSupabase().rpc("place_market_bid",{p_vehicle_id:v.id,p_bidder_name:bidderName,p_bidder_phone:bidderPhone,p_amount:amount});if(error)throw error;setBidMessage(`Oferta $${Number((data as any)?.current_bid??amount).toLocaleString("en-US")} została przyjęta.`);setBidderName("");setBidderPhone("");await load()}catch(err){setBidMessage(err instanceof Error?err.message:"Nie udało się złożyć oferty.")}finally{setBidBusy(false)}};
 if(loading)return <main className="market"><div className="market-empty">ŁADOWANIE OFERTY…</div></main>;
 if(!v)return <main className="market"><div className="market-empty">TEJ OFERTY JUŻ NIE MA.</div></main>;
 const photos=[v.image_url,...(v.gallery||[])].filter(Boolean) as string[];const isAuction=v.sale_mode==="auction";const ended=Boolean(isAuction&&v.auction_ends_at&&new Date(v.auction_ends_at)<=new Date());const current=v.auction_current_bid??v.auction_start_price??0;const increment=v.auction_min_increment||500;const nextMinimum=current+increment;
 return <main className="market"><header className="market-nav"><a href="/" className="market-logo">STREET<span>SCOPE</span></a><nav><a href="/market">← TOW & TRADE</a></nav></header><section className="vehicle-detail"><div className="vehicle-detail-head"><div><p>STREETSCOPE × TOW & TRADE</p><h1>{v.brand}<br/><em>{v.model}</em></h1><span>{isAuction?(ended?"LICYTACJA ZAKOŃCZONA":"LICYTACJA"):v.status==="sold"?"SPRZEDANE":v.status==="reserved"?"ZAREZERWOWANE":"NA SPRZEDAŻ"}</span></div><strong>${Number(isAuction?current:v.price||0).toLocaleString("en-US")}</strong></div>{photos[0]&&<img className="vehicle-cover" src={photos[0]} alt={`${v.brand} ${v.model}`}/>}<div className="vehicle-specs"><div><small>ROK</small><b>{v.year||"—"}</b></div><div><small>PRZEBIEG</small><b>{v.mileage!=null?`${v.mileage.toLocaleString("pl-PL")} MI`:"—"}</b></div><div><small>SILNIK</small><b>{v.engine||"—"}</b></div><div><small>NAPĘD</small><b>{v.drivetrain||"—"}</b></div><div><small>SKRZYNIA BIEGÓW</small><b>{v.transmission||"—"}</b></div><div><small>KOLOR</small><b>{v.color||"—"}</b></div></div>
 {isAuction&&<section className="auction-panel"><div className="auction-summary"><p className="kicker">LICYTACJA TOW & TRADE</p><h2>{ended?"LICYTACJA ZAKOŃCZONA":"LICYTUJ TEN WÓZ"}</h2><div className="auction-numbers"><div><small>{v.auction_current_bid?"AKTUALNA OFERTA":"CENA STARTOWA"}</small><b>${Number(current).toLocaleString("en-US")}</b></div><div><small>MINIMALNE PODBICIE</small><b>${Number(increment).toLocaleString("en-US")}</b></div><div><small>LICZBA OFERT</small><b>{v.auction_bid_count||0}</b></div><div><small>KONIEC</small><b>{v.auction_ends_at?new Date(v.auction_ends_at).toLocaleString("pl-PL"):"—"}</b></div></div></div>{!ended&&v.status==="available"?<form className="auction-bid-form" onSubmit={placeBid}><label>IMIĘ I NAZWISKO / POSTAĆ<input required minLength={2} value={bidderName} onChange={e=>setBidderName(e.target.value)} placeholder="np. Daichi Kuroda"/></label><label>NUMER TELEFONU<input required value={bidderPhone} onChange={e=>setBidderPhone(e.target.value)} placeholder="Numer IC"/></label><label>KWOTA OFERTY $<input required type="number" min={nextMinimum} step="1" value={bidAmount} onChange={e=>setBidAmount(e.target.value)}/><small>Minimum teraz: ${Number(nextMinimum).toLocaleString("en-US")}</small></label><button disabled={bidBusy}>{bidBusy?"SKŁADAM OFERTĘ…":`LICYTUJ $${Number(bidAmount||0).toLocaleString("en-US")}`}</button>{bidMessage&&<p className="auction-message">{bidMessage}</p>}</form>:<div className="auction-closed">{v.status!=="available"?"Ta oferta nie przyjmuje już nowych licytacji.":"Czas na składanie ofert minął."}</div>}</section>}
 <section className="vehicle-copy"><div><p className="kicker">OFERTA TOW & TRADE</p><h2>O TYM WOZIE</h2><p>{v.description||"Tow & Trade nie dodało jeszcze opisu tej oferty."}</p></div><aside><small>SPRZEDAJĄCY</small><h3>{v.seller_name||"Tow & Trade"}</h3><p>{v.seller_phone||"Kontakt bezpośrednio przez Tow & Trade."}</p><a href="/market">WRÓĆ DO OFERT →</a></aside></section>{photos.length>1&&<section className="vehicle-gallery">{photos.slice(1).map((url,i)=><img src={url} alt="" key={`${url}-${i}`}/>)}</section>}</section></main>;
}