"use client";

import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { getSupabase } from "../../../lib/supabase";
import "../market.css";

type Vehicle={id:number;brand:string;model:string;year:number|null;price:number;mileage:number|null;drivetrain:string|null;transmission:string|null;engine:string|null;color:string|null;description:string|null;image_url:string|null;gallery:string[]|null;seller_name:string|null;seller_phone:string|null;status:string;sale_mode:"sale"|"auction";auction_start_price:number|null;auction_min_increment:number|null;auction_current_bid:number|null;auction_bid_count:number|null;auction_ends_at:string|null;auction_deposit_amount:number|null;auction_bank_account:string|null};
type Bid={id:number;vehicle_id:number;bidder_name:string|null;amount:number|null;created_at:string};
type Access={exists?:boolean;status?:"pending"|"approved"|"rejected";bidder_name?:string;auction_number?:string;deposit_amount?:number;bank_account?:string};

export default function MarketVehiclePage(){
 const params=useParams<{id:string}>();
 const vehicleId=Number(params.id);
 const [v,setV]=useState<Vehicle|null>(null),[bids,setBids]=useState<Bid[]>([]),[loading,setLoading]=useState(true),[endedState,setEndedState]=useState(false);
 const [name,setName]=useState(""),[bidAmount,setBidAmount]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[access,setAccess]=useState<Access|null>(null),[token,setToken]=useState(""),[rulesAccepted,setRulesAccepted]=useState(false),[visibleBids,setVisibleBids]=useState(5);
 const supabase=()=>getSupabase();
 const ensureToken=()=>{let t=localStorage.getItem(`tow-auction-${params.id}`)||"";if(!t){t=crypto.randomUUID();localStorage.setItem(`tow-auction-${params.id}`,t)}if(t!==token)setToken(t);return t};
 const checkAccess=async(t?:string)=>{try{const tok=t||token||ensureToken();const {data,error}=await supabase().rpc("get_market_auction_access",{p_vehicle_id:vehicleId,p_bidder_token:tok});if(error)return;setAccess((data as Access)||null)}catch{}};
 const refreshBids=async()=>{try{const {data,error}=await supabase().from("market_auction_bids").select("id,vehicle_id,bidder_name,amount,created_at").eq("vehicle_id",vehicleId).order("amount",{ascending:false}).order("created_at",{ascending:false});if(!error)setBids((data as Bid[]|null)??[])}catch{}};
 const applyVehicle=(row:Vehicle)=>{setV(row);if(row.sale_mode!=="auction"){setEndedState(false);setBids([]);setAccess(null);return}const rowEnded=Boolean(row.auction_ends_at&&new Date(row.auction_ends_at).getTime()<=Date.now());setEndedState(rowEnded||row.status!=="available");const next=(row.auction_current_bid??row.auction_start_price??0)+(row.auction_min_increment||500);setBidAmount(prev=>{const currentInput=Number(prev);return !prev||!Number.isFinite(currentInput)||currentInput<next?String(next):prev})};
 const loadInitial=async()=>{try{const {data,error}=await supabase().from("market_vehicles").select("*").eq("id",vehicleId).maybeSingle();if(error){setMessage(`Nie udało się załadować oferty: ${error.message}`);return}const row=(data as Vehicle|null)??null;if(!row){setV(null);return}applyVehicle(row);if(row.sale_mode==="auction"){await refreshBids();const rowEnded=Boolean(row.auction_ends_at&&new Date(row.auction_ends_at).getTime()<=Date.now());if(!rowEnded&&row.status==="available")void checkAccess()}}catch(err){setMessage(err instanceof Error?`Nie udało się załadować oferty: ${err.message}`:"Nie udało się załadować oferty.")}finally{setLoading(false)}};
 useEffect(()=>{if(typeof window!=="undefined"){ensureToken();void loadInitial()}},[params.id]);
 useEffect(()=>{setVisibleBids(5)},[params.id]);
 useEffect(()=>{if(!v||v.sale_mode!=="auction"){setEndedState(false);return}if(v.status!=="available"){setEndedState(true);return}if(!v.auction_ends_at){setEndedState(false);return}const endAt=new Date(v.auction_ends_at).getTime();if(!Number.isFinite(endAt)){setEndedState(false);return}const remaining=endAt-Date.now();if(remaining<=0){setEndedState(true);return}setEndedState(false);const timer=window.setTimeout(()=>setEndedState(true),Math.min(remaining+50,2147483000));return()=>window.clearTimeout(timer)},[v?.id,v?.sale_mode,v?.status,v?.auction_ends_at]);
 useEffect(()=>{if(typeof window==="undefined"||!Number.isFinite(vehicleId))return;const sb=supabase();let active=true;let bidsRefreshing=false;const refreshBidData=async()=>{if(!active||bidsRefreshing)return;bidsRefreshing=true;try{await refreshBids()}finally{bidsRefreshing=false}};const channel=sb.channel(`tow-auction-live-${vehicleId}`).on("postgres_changes",{event:"*",schema:"public",table:"market_auction_bids",filter:`vehicle_id=eq.${vehicleId}`},()=>{void refreshBidData()}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"market_vehicles",filter:`id=eq.${vehicleId}`},payload=>{if(!active)return;const nextVehicle=payload.new as Vehicle;if(nextVehicle&&Number(nextVehicle.id)===vehicleId)applyVehicle(nextVehicle)}).subscribe();return()=>{active=false;void sb.removeChannel(channel)}},[params.id]);
 const requestAccess=async(e:FormEvent)=>{e.preventDefault();if(!rulesAccepted){setMessage("Musisz zaakceptować regulamin licytacji.");return}setBusy(true);setMessage("");try{const tok=token||ensureToken();const {data,error}=await supabase().rpc("request_market_auction_access",{p_vehicle_id:vehicleId,p_bidder_name:name,p_bidder_phone:"",p_bidder_token:tok});if(error)throw error;const nextAccess=data as Access;setAccess(nextAccess);let webhookWarning="";try{const webhookResponse=await fetch("/api/auction-application",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({auctionNumber:nextAccess?.auction_number||String(vehicleId).padStart(4,"0"),vehicle:v?`${v.brand} ${v.model}`:"Pojazd",bidderName:name,depositAmount:nextAccess?.deposit_amount??v?.auction_deposit_amount??5000,bankAccount:nextAccess?.bank_account??v?.auction_bank_account??""})});const webhookResult=await webhookResponse.json().catch(()=>null);if(!webhookResponse.ok||!webhookResult?.ok){webhookWarning=webhookResult?.error||`Webhook zwrócił błąd ${webhookResponse.status}.`}}catch(err){webhookWarning=err instanceof Error?err.message:"Nie udało się połączyć z webhookiem."}setMessage(webhookWarning?`ZGŁOSZENIE ZAPISANE, ale powiadomienie Discord nie zostało wysłane: ${webhookWarning}`:"ZGŁOSZENIE WYSŁANE. Wpłać depozyt i poczekaj na akceptację dealera.")}catch(err){setMessage(err instanceof Error?err.message:"Nie udało się wysłać zgłoszenia.")}finally{setBusy(false)}};
 const placeBid=async(e:FormEvent)=>{e.preventDefault();if(!v)return;setBusy(true);setMessage("");try{const endsAt=v.auction_ends_at?new Date(v.auction_ends_at).getTime():0;if(endedState||v.status!=="available"||(endsAt>0&&Date.now()>=endsAt))throw new Error("Licytacja została już zakończona.");const current=v.auction_current_bid??v.auction_start_price??0,increment=v.auction_min_increment||500,nextMinimum=current+increment,amount=Number(bidAmount);if(!Number.isFinite(amount)||amount<nextMinimum)throw new Error(`Minimalna oferta to $${nextMinimum.toLocaleString("en-US")}.`);const tok=token||ensureToken();const {data,error}=await supabase().rpc("place_market_bid_verified",{p_vehicle_id:v.id,p_bidder_token:tok,p_amount:amount});if(error)throw new Error(error.message||"Nie udało się złożyć oferty.");const acceptedBid=Number((data as any)?.current_bid??amount);setV(prev=>prev?{...prev,auction_current_bid:acceptedBid,auction_bid_count:(prev.auction_bid_count??0)+1}:prev);setBidAmount(String(acceptedBid+(v.auction_min_increment||500)));setMessage(`Oferta $${acceptedBid.toLocaleString("en-US")} została przyjęta.`);await refreshBids()}catch(err){setMessage(err instanceof Error?err.message:"Nie udało się złożyć oferty.")}finally{setBusy(false)}};
 if(loading)return <main className="market"><div className="market-empty">ŁADOWANIE OFERTY…</div></main>;
 if(!v)return <main className="market"><div className="market-empty">{message||"TEJ OFERTY JUŻ NIE MA."}</div></main>;
 const photos=[v.image_url,...(v.gallery||[])].filter(Boolean) as string[],isAuction=v.sale_mode==="auction",closed=isAuction&&(endedState||v.status!=="available"),current=v.auction_current_bid??v.auction_start_price??0,increment=v.auction_min_increment||500,nextMinimum=current+increment,auctionNo=String(v.id).padStart(4,"0"),deposit=v.auction_deposit_amount??5000,bankAccount=v.auction_bank_account||"NUMER RACHUNKU NIE ZOSTAŁ JESZCZE USTAWIONY",winner=bids[0],winnerName=winner?.bidder_name?String(winner.bidder_name).toUpperCase():"",winnerAmount=Number(winner?.amount??0),accessStatus=access?.status??null;
 return <main className="market"><header className="market-nav"><a href="/" className="market-logo">STREET<span>SCOPE</span></a><nav>{isAuction&&<a href="/market/regulamin">REGULAMIN</a>}<a href="/market">← TOW & TRADE</a></nav></header><section className="vehicle-detail"><div className="vehicle-detail-head"><div><p>STREETSCOPE × TOW & TRADE</p><h1>{v.brand}<br/><em>{v.model}</em></h1><span>{isAuction?(closed?"LICYTACJA ZAKOŃCZONA":`LICYTACJA #${auctionNo}`):v.status==="sold"?"SPRZEDANE":v.status==="reserved"?"ZAREZERWOWANE":"NA SPRZEDAŻ"}</span></div><strong>${Number(isAuction?current:v.price||0).toLocaleString("en-US")}</strong></div>{photos[0]&&<img className="vehicle-cover" src={photos[0]} alt={`${v.brand} ${v.model}`}/>}<div className="vehicle-specs"><div><small>ROK</small><b>{v.year||"—"}</b></div><div><small>PRZEBIEG</small><b>{v.mileage!=null?`${v.mileage.toLocaleString("pl-PL")} MI`:"—"}</b></div><div><small>SILNIK</small><b>{v.engine||"—"}</b></div><div><small>NAPĘD</small><b>{v.drivetrain||"—"}</b></div><div><small>SKRZYNIA</small><b>{v.transmission||"—"}</b></div><div><small>KOLOR</small><b>{v.color||"—"}</b></div></div>
 {isAuction&&<><section className="auction-panel"><div className="auction-summary"><p className="kicker">LICYTACJA #{auctionNo}</p><h2>{closed?"LICYTACJA ZAKOŃCZONA":"UDZIAŁ W LICYTACJI"}</h2><div className="auction-numbers"><div><small>{v.auction_current_bid?"AKTUALNA OFERTA":"CENA STARTOWA"}</small><b>${Number(current).toLocaleString("en-US")}</b></div><div><small>MINIMALNE PODBICIE</small><b>${Number(increment).toLocaleString("en-US")}</b></div><div><small>DEPOZYT</small><b>${Number(deposit).toLocaleString("en-US")}</b></div><div><small>KONIEC</small><b>{v.auction_ends_at?new Date(v.auction_ends_at).toLocaleString("pl-PL"):"—"}</b></div></div><div className="auction-access-box"><small>RACHUNEK DO WPŁATY DEPOZYTU</small><h3>{bankAccount}</h3><p>Tytuł przelewu: <strong>LICYTACJA #{auctionNo} — IMIĘ I NAZWISKO</strong></p><p>Po przelewie wyślij zgłoszenie. Dealer zweryfikuje wpłatę i odblokuje możliwość licytowania.</p></div></div>
 {!closed&&(!accessStatus||accessStatus==="rejected")&&<form className="auction-bid-form" onSubmit={requestAccess}><h3>DOŁĄCZ DO LICYTACJI</h3><label>IMIĘ I NAZWISKO<input required minLength={2} value={name} onChange={e=>setName(e.target.value)} placeholder="np. Daichi Kuroda"/></label><label className="auction-rules-check"><input type="checkbox" checked={rulesAccepted} onChange={e=>setRulesAccepted(e.target.checked)}/><span>Zapoznałem się i akceptuję <a href="/market/regulamin" target="_blank">Regulamin Licytacji Tow & Trade</a>.</span></label><button disabled={busy||!rulesAccepted}>{busy?"WYSYŁAM…":"WYŚLIJ ZGŁOSZENIE"}</button>{accessStatus==="rejected"&&<small>Poprzednie zgłoszenie zostało odrzucone. Możesz wysłać je ponownie.</small>}</form>}
 {!closed&&accessStatus==="pending"&&<div className="auction-access-box pending"><small>OCZEKUJE NA AKCEPTACJĘ</small><h3>WPŁAĆ DEPOZYT ${Number(access?.deposit_amount??deposit).toLocaleString("en-US")}</h3><p>Rachunek Tow & Trade: <b>{access?.bank_account||bankAccount}</b>.</p><p>Tytuł przelewu: <strong>LICYTACJA #{access?.auction_number||auctionNo} — {access?.bidder_name}</strong></p><p className="auction-binding-note">Wpłacenie depozytu i udział w licytacji oznacza akceptację regulaminu. Zwycięska oferta jest wiążąca.</p><button onClick={()=>checkAccess()} disabled={busy}>SPRAWDŹ STATUS</button></div>}
 {!closed&&accessStatus==="approved"&&<form className="auction-bid-form" onSubmit={placeBid}><div className="auction-approved"><small>ZWERYFIKOWANY UCZESTNIK</small><b>{access?.bidder_name}</b></div><p className="auction-binding-note">Każda oferta jest wiążąca. Zwycięzca ma 3 dni od końca licytacji na uregulowanie pozostałej części ceny.</p><label>KWOTA OFERTY $<input required type="number" min={nextMinimum} step="1" value={bidAmount} onChange={e=>setBidAmount(e.target.value)}/><small>Minimum teraz: ${Number(nextMinimum).toLocaleString("en-US")}</small></label><button disabled={busy}>{busy?"SKŁADAM OFERTĘ…":`LICYTUJ $${Number(bidAmount||0).toLocaleString("en-US")}`}</button></form>}
 {closed&&<div className="auction-closed">{winner&&winnerName?<><small>LICYTACJA ZAKOŃCZONA</small><strong>WYGRAŁ: {winnerName}</strong><b>${winnerAmount.toLocaleString("en-US")}</b></>:<><small>LICYTACJA ZAKOŃCZONA</small><strong>BRAK ZŁOŻONYCH OFERT</strong></>}</div>}{message&&<p className="auction-message full-auction-message">{message}</p>}</section>
 <section className="auction-history"><div className="auction-history-head"><div><p className="kicker">HISTORIA LICYTACJI</p><h2>KTO ILE DAJE</h2></div><b>{bids.length} {bids.length===1?"OFERTA":"OFERT"}</b></div>{bids.length>0?<><div className="auction-bid-list">{bids.slice(0,visibleBids).map((bid,index)=><div className={`auction-bid-row ${index===0?"leader":""}`} key={bid.id}><span>{index===0?"NAJWYŻSZA":"OFERTA"}</span><strong>{bid.bidder_name||"NIEZNANY UCZESTNIK"}</strong><b>${Number(bid.amount??0).toLocaleString("en-US")}</b><small>{new Date(bid.created_at).toLocaleString("pl-PL")}</small></div>)}</div>{bids.length>5&&<div style={{display:"flex",justifyContent:"center",padding:"18px",borderTop:"1px solid #242424"}}><button type="button" onClick={()=>setVisibleBids(visibleBids>=bids.length?5:Math.min(visibleBids+5,bids.length))} style={{background:"#171717",border:"1px solid #3a3a3a",color:"#fff",padding:"12px 22px",fontWeight:950,fontSize:"11px",letterSpacing:"1px",cursor:"pointer"}}>{visibleBids>=bids.length?"ZWIŃ HISTORIĘ":`ROZWIŃ WIĘCEJ · ${bids.length-visibleBids} POZOSTAŁYCH`}</button></div>}</>:<div className="auction-no-bids">JESZCZE NIKT NIE ZALICYTOWAŁ.</div>}</section></>}
 <section className="vehicle-copy"><div><p className="kicker">OFERTA TOW & TRADE</p><h2>O TYM WOZIE</h2><p>{v.description||"Tow & Trade nie dodało jeszcze opisu tej oferty."}</p></div><aside><small>SPRZEDAJĄCY</small><h3>{v.seller_name||"Tow & Trade"}</h3><p>{v.seller_phone||"Kontakt bezpośrednio przez Tow & Trade."}</p><a href="/market">WRÓĆ DO OFERT →</a></aside></section>{photos.length>1&&<section className="vehicle-gallery">{photos.slice(1).map((url,i)=><img src={url} alt="" key={`${url}-${i}`}/>)}</section>}</section></main>;
}