import "../market.css";

const sections=[
 {title:"§1. Warunki udziału w licytacji",items:["Udział w licytacji organizowanej przez Tow & Trade wymaga wcześniejszego wpłacenia ustalonego depozytu.","Depozyt jest warunkiem dopuszczenia uczestnika do licytacji.","Uczestnik, który nie wpłaci depozytu przed rozpoczęciem licytacji, nie zostanie dopuszczony do składania ofert."]},
 {title:"§2. Depozyt uczestnika",items:["W przypadku przegrania licytacji depozyt zostaje zwrócony uczestnikowi.","W przypadku wygrania licytacji depozyt zostaje zaliczony na poczet końcowej ceny wylicytowanego pojazdu.","Depozyt nie stanowi dodatkowej opłaty za pojazd, lecz zabezpieczenie udziału w licytacji i realizacji zwycięskiej oferty."]},
 {title:"§3. Zwycięska oferta",items:["Złożenie najwyższej oferty i zakończenie licytacji na korzyść uczestnika oznacza obowiązek zakupu wylicytowanego pojazdu.","Zwycięzca zobowiązany jest do uregulowania pozostałej części ceny pojazdu w terminie 3 dni od końca licytacji.","Zwycięzca nie może jednostronnie wycofać się z zakupu po zakończeniu licytacji bez zgody Tow & Trade."]},
 {title:"§4. Rezygnacja z zakupu",items:["Jeżeli zwycięzca odmówi zakupu pojazdu, nie dokona wymaganej płatności lub bez uzasadnionej przyczyny wycofa się z transakcji, Tow & Trade ma prawo zatrzymać wpłacony depozyt.","Zatrzymanie depozytu stanowi konsekwencję niewywiązania się zwycięzcy z obowiązku zakupu.","W przypadku rezygnacji przez zwycięzcę Tow & Trade może również ponownie wystawić pojazd na licytację."]},
 {title:"§5. Zasady licytacji",items:["Każda złożona oferta jest traktowana jako wiążąca.","Uczestnik przed złożeniem oferty akceptuje stan techniczny i wizualny pojazdu.","Tow & Trade nie ponosi odpowiedzialności za decyzję uczestnika dotyczącą wysokości złożonej oferty.","W przypadku sporów dotyczących przebiegu licytacji ostateczną decyzję podejmuje przedstawiciel Tow & Trade, z zastrzeżeniem zasad obowiązujących w Los Santos i stanie San Andreas."]},
];

export default function AuctionRulesPage(){return <main className="market"><header className="market-nav"><a href="/" className="market-logo">STREET<span>SCOPE</span></a><nav><a href="/market/licytacje">← LICYTACJE</a></nav></header><article className="auction-rules-page"><p className="kicker">TOW & TRADE · LOS SANTOS, SAN ANDREAS</p><h1>REGULAMIN<br/><em>LICYTACJI.</em></h1><p className="auction-rules-lead">Zasady udziału w licytacjach pojazdów organizowanych przez Tow & Trade.</p>{sections.map(s=><section key={s.title}><h2>{s.title}</h2><ol>{s.items.map(x=><li key={x}>{x}</li>)}</ol></section>)}<section><h2>§6. Akceptacja regulaminu</h2><p>Wpłacenie depozytu oraz przystąpienie do licytacji oznacza pełną akceptację niniejszego regulaminu oraz zobowiązanie do przestrzegania wszystkich określonych w nim zasad.</p></section><footer><b>TOW & TRADE</b><span>Los Santos, San Andreas</span></footer></article></main>;}