-- ============================================
-- TOW & TRADE — LICYTACJE
-- Uruchom w Supabase SQL Editor po market_setup.sql
-- ============================================

alter table public.market_vehicles
  add column if not exists sale_mode text not null default 'sale',
  add column if not exists auction_start_price integer,
  add column if not exists auction_min_increment integer not null default 500,
  add column if not exists auction_current_bid integer,
  add column if not exists auction_bid_count integer not null default 0,
  add column if not exists auction_ends_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'market_vehicles_sale_mode_check'
  ) then
    alter table public.market_vehicles
      add constraint market_vehicles_sale_mode_check
      check (sale_mode in ('sale','auction'));
  end if;
end $$;

create table if not exists public.market_auction_bids (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.market_vehicles(id) on delete cascade,
  bidder_name text not null,
  bidder_phone text not null,
  amount integer not null,
  created_at timestamptz not null default now()
);

alter table public.market_auction_bids enable row level security;

-- Oferty aut pozostają publiczne do odczytu. Samych danych licytujących
-- nie wystawiamy publicznie przez tabelę.
revoke all on table public.market_auction_bids from anon;
revoke all on table public.market_auction_bids from authenticated;

grant select, insert, update, delete on table public.market_auction_bids to authenticated;
grant usage, select on sequence public.market_auction_bids_id_seq to authenticated;

-- Dealerzy/redakcja mogą podejrzeć pełną historię ofert.
drop policy if exists "auction bids staff read" on public.market_auction_bids;
create policy "auction bids staff read"
on public.market_auction_bids
for select
to authenticated
using (true);

-- Atomowe składanie oferty. Gracz nie dostaje bezpośredniego INSERT do tabeli,
-- tylko wywołuje tę funkcję. Blokada wiersza chroni przed dwoma ofertami naraz.
create or replace function public.place_market_bid(
  p_vehicle_id bigint,
  p_bidder_name text,
  p_bidder_phone text,
  p_amount integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v public.market_vehicles%rowtype;
  v_min integer;
begin
  if length(trim(coalesce(p_bidder_name,''))) < 2 then
    raise exception 'Podaj imię i nazwisko / nazwę postaci.';
  end if;
  if length(trim(coalesce(p_bidder_phone,''))) < 3 then
    raise exception 'Podaj numer telefonu.';
  end if;

  select * into v
  from public.market_vehicles
  where id = p_vehicle_id
  for update;

  if not found then
    raise exception 'Ta oferta nie istnieje.';
  end if;
  if v.sale_mode <> 'auction' then
    raise exception 'Ten pojazd nie jest wystawiony na licytację.';
  end if;
  if v.status <> 'available' then
    raise exception 'Ta licytacja nie jest aktywna.';
  end if;
  if v.auction_ends_at is null or v.auction_ends_at <= now() then
    raise exception 'Licytacja już się zakończyła.';
  end if;

  v_min := coalesce(v.auction_current_bid, v.auction_start_price, 0)
           + greatest(coalesce(v.auction_min_increment,500),1);

  if p_amount < v_min then
    raise exception 'Minimalna kolejna oferta to $%.', v_min;
  end if;

  insert into public.market_auction_bids(vehicle_id,bidder_name,bidder_phone,amount)
  values (p_vehicle_id, trim(p_bidder_name), trim(p_bidder_phone), p_amount);

  update public.market_vehicles
  set auction_current_bid = p_amount,
      auction_bid_count = coalesce(auction_bid_count,0) + 1,
      updated_at = now()
  where id = p_vehicle_id;

  return jsonb_build_object(
    'ok', true,
    'current_bid', p_amount,
    'bid_count', coalesce(v.auction_bid_count,0) + 1,
    'next_minimum', p_amount + greatest(coalesce(v.auction_min_increment,500),1)
  );
end;
$$;

revoke all on function public.place_market_bid(bigint,text,text,integer) from public;
grant execute on function public.place_market_bid(bigint,text,text,integer) to anon, authenticated;

create index if not exists market_auction_bids_vehicle_idx
on public.market_auction_bids(vehicle_id, created_at desc);

create index if not exists market_vehicles_sale_mode_idx
on public.market_vehicles(sale_mode);

create index if not exists market_vehicles_auction_ends_idx
on public.market_vehicles(auction_ends_at);
