"use client";

import { FormEvent, useEffect, useState } from "react";
import { getSupabase } from "../../../lib/supabase";
import "./team.css";

const CHIEF = "kujalowicze@gmail.com";
type Staff = { id:number; email:string; display_name:string|null; role:"editor"|"chief"; active:boolean; created_at:string };

export default function ZespolPage() {
  const [ok,setOk]=useState<boolean|null>(null); const [staff,setStaff]=useState<Staff[]>([]); const [email,setEmail]=useState(""); const [name,setName]=useState(""); const [accountRole,setAccountRole]=useState<"editor"|"chief">("editor"); const [message,setMessage]=useState(""); const client=()=>getSupabase();
  async function load(){const {data,error}=await client().from("staff_accounts").select("id,email,display_name,role,active,created_at").order("created_at",{ascending:false});if(error)setMessage(error.message);setStaff((data as Staff[]|null)??[]);}
  useEffect(()=>{client().auth.getUser().then(async ({data})=>{const email=data.user?.email?.toLowerCase()||"";const {data:person}=await client().from("staff_accounts").select("role,active").eq("email",email).maybeSingle();const allowed=Boolean(person?.active&&person.role==="chief");setOk(allowed);if(allowed)await load();});},[]);
  async function add(event:FormEvent){event.preventDefault();const normalized=email.trim().toLowerCase();const {error}=await client().from("staff_accounts").upsert({email:normalized,display_name:name.trim()||null,role:accountRole,active:true},{onConflict:"email"});setMessage(error?error.message:`Zapisano konto ${normalized} jako ${accountRole === "chief" ? "naczelny" : "redaktor"}.`);if(!error){setEmail("");setName("");setAccountRole("editor");await load();}}
  async function toggle(person:Staff){const {error}=await client().from("staff_accounts").update({active:!person.active}).eq("id",person.id);setMessage(error?error.message:person.active?"Konto wyłączone.":"Konto aktywne.");if(!error)await load();}
  async function changeRole(person:Staff, role:"editor"|"chief"){if(person.email===CHIEF){setMessage("Główne konto naczelnego zawsze zachowuje tę rolę.");return;}if(!window.confirm(`Nadać ${person.email} rolę: ${role === "chief" ? "NACZELNY" : "REDAKTOR"}?`))return;const {error}=await client().from("staff_accounts").update({role}).eq("id",person.id);setMessage(error?error.message:"Uprawnienia zapisane.");if(!error)await load();}
  if(ok===null)return <main className="team-page">ŁADOWANIE…</main>;if(!ok)return <main className="team-page"><h1>DOSTĘP ZAMKNIĘTY.</h1></main>;
  return <main className="team-page"><header><a href="/" className="wordmark">STREET<span>SCOPE</span></a><nav><a href="/redakcja/material">EDYTOR</a><a href="/redakcja/zarzadzaj">AKCEPTACJA</a></nav></header><section className="team-head"><p className="kicker"><i/> NACZELNY</p><h1>ZESPÓŁ<br/><em>REDAKCJI.</em></h1><p>Dodaj pracownika albo zmień jego rolę. Redaktor wysyła materiały do akceptacji; naczelny może publikować, akceptować i zarządzać zespołem.</p></section><section className="team-grid"><form onSubmit={add}><p className="kicker"><i/> NOWE KONTO</p><label>NAZWA / IMIĘ<input value={name} onChange={e=>setName(e.target.value)} placeholder="np. Izumi Daigo" /></label><label>E-MAIL PRACOWNIKA<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="redaktor@email.pl" /></label><label>ROLA<select value={accountRole} onChange={e=>setAccountRole(e.target.value as "editor"|"chief")}><option value="editor">REDAKTOR — pisze i wysyła</option><option value="chief">NACZELNY — pełny dostęp</option></select></label><button className="primary">ZAPISZ KONTO →</button><small>{message}</small></form><div><p className="kicker"><i/> AKTYWNE KONTA</p><div className="staff-list">{staff.map(person=><article key={person.id}><div><b>{person.display_name||"REDAKTOR"}</b><span>{person.email}</span><em>{person.role==="chief"?"NACZELNY":person.active?"REDAKTOR":"WYŁĄCZONE"}</em></div><aside>{person.email!==CHIEF&&<select value={person.role} onChange={e=>changeRole(person,e.target.value as "editor"|"chief")} aria-label={`Rola ${person.email}`}><option value="editor">REDAKTOR</option><option value="chief">NACZELNY</option></select>}{person.email!==CHIEF&&<button onClick={()=>toggle(person)}>{person.active?"WYŁĄCZ":"WŁĄCZ"}</button>}</aside></article>)}</div></div></section></main>;
}
