"use client";

import { FormEvent, useEffect, useState } from "react";
import { getSupabase } from "../../../lib/supabase";
import "./team.css";

const OWNER = "kujalowicze@gmail.com";
type StaffRole = "editor_in_chief"|"deputy_editor_in_chief"|"journalist";
type Staff = { id:number; email:string; first_name:string|null; last_name:string|null; display_name:string|null; role:StaffRole; active:boolean; created_at:string };
const roleName:Record<StaffRole,string>={editor_in_chief:"REDAKTOR NACZELNY",deputy_editor_in_chief:"ZASTĘPCA REDAKTORA NACZELNEGO",journalist:"DZIENNIKARZ"};
const fullName=(person:{first_name?:string|null;last_name?:string|null;display_name?:string|null})=>[person.first_name,person.last_name].filter(Boolean).join(" ")||person.display_name||"CZŁONEK REDAKCJI";

export default function ZespolPage() {
  const [ok,setOk]=useState<boolean|null>(null); const [staff,setStaff]=useState<Staff[]>([]); const [email,setEmail]=useState(""); const [firstName,setFirstName]=useState(""); const [lastName,setLastName]=useState(""); const [accountRole,setAccountRole]=useState<StaffRole>("journalist"); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false); const client=()=>getSupabase();
  async function load(){const {data,error}=await client().from("staff_accounts").select("id,email,first_name,last_name,display_name,role,active,created_at").order("created_at",{ascending:false});if(error)setMessage(error.message);setStaff((data as Staff[]|null)??[]);}
  useEffect(()=>{client().auth.getUser().then(async ({data})=>{const email=data.user?.email?.toLowerCase()||"";const {data:person}=await client().from("staff_accounts").select("role,active").eq("email",email).maybeSingle();const allowed=Boolean(person?.active&&["editor_in_chief","deputy_editor_in_chief"].includes(person.role));setOk(allowed);if(allowed)await load();});},[]);
  async function add(event:FormEvent){event.preventDefault();setSaving(true);const normalized=email.trim().toLowerCase();const display=[firstName.trim(),lastName.trim()].filter(Boolean).join(" ");const {error}=await client().from("staff_accounts").upsert({email:normalized,first_name:firstName.trim()||null,last_name:lastName.trim()||null,display_name:display||null,role:accountRole,active:true},{onConflict:"email"});setSaving(false);setMessage(error?error.message:`Zapisano konto ${normalized}: ${roleName[accountRole]}.`);if(!error){setEmail("");setFirstName("");setLastName("");setAccountRole("journalist");await load();}}
  async function saveName(person:Staff){const first=window.prompt("Imię:",person.first_name||"");if(first===null)return;const last=window.prompt("Nazwisko:",person.last_name||"");if(last===null)return;const display=[first.trim(),last.trim()].filter(Boolean).join(" ");const {error}=await client().from("staff_accounts").update({first_name:first.trim()||null,last_name:last.trim()||null,display_name:display||null}).eq("id",person.id);setMessage(error?error.message:"Dane autora zapisane.");if(!error)await load();}
  async function toggle(person:Staff){const {error}=await client().from("staff_accounts").update({active:!person.active}).eq("id",person.id);setMessage(error?error.message:person.active?"Konto wyłączone.":"Konto aktywne.");if(!error)await load();}
  async function changeRole(person:Staff, role:StaffRole){if(person.email===OWNER){setMessage("Główne konto Redaktora Naczelnego zachowuje tę rolę.");return;}if(!window.confirm(`Nadać ${person.email} rolę: ${roleName[role]}?`))return;const {error}=await client().from("staff_accounts").update({role}).eq("id",person.id);setMessage(error?error.message:"Uprawnienia zapisane.");if(!error)await load();}
  if(ok===null)return <main className="team-page">ŁADOWANIE…</main>;if(!ok)return <main className="team-page"><h1>DOSTĘP ZAMKNIĘTY.</h1></main>;
  return <main className="team-page"><header><a href="/" className="wordmark">STREET<span>SCOPE</span></a><nav><a href="/redakcja/material">EDYTOR</a><a href="/redakcja/zarzadzaj">AKCEPTACJA</a><a href="/redakcja/rekrutacja">REKRUTACJA</a></nav></header><section className="team-head"><p className="kicker"><i/> ZARZĄDZANIE ZESPOŁEM</p><h1>ZESPÓŁ<br/><em>REDAKCJI.</em></h1><p>Wpisz pełne dane dla każdego konta — ten podpis pojawi się automatycznie pod opublikowanym artykułem.</p></section><section className="team-grid"><form onSubmit={add}><p className="kicker"><i/> NOWE KONTO</p><label>IMIĘ<input value={firstName} onChange={e=>setFirstName(e.target.value)} placeholder="Izumi" /></label><label>NAZWISKO<input value={lastName} onChange={e=>setLastName(e.target.value)} placeholder="Daigo" /></label><label>E-MAIL PRACOWNIKA<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="redaktor@email.pl" /></label><label>ROLA<select value={accountRole} onChange={e=>setAccountRole(e.target.value as StaffRole)}><option value="editor_in_chief">REDAKTOR NACZELNY — pełny dostęp</option><option value="deputy_editor_in_chief">ZASTĘPCA NACZELNEGO — pełny dostęp</option><option value="journalist">DZIENNIKARZ — pisze i wysyła</option></select></label><button className="primary" disabled={saving}>{saving?"ZAPIS…":"ZAPISZ KONTO →"}</button><small>{message}</small></form><div><p className="kicker"><i/> AKTYWNE KONTA</p><div className="staff-list">{staff.map(person=><article key={person.id}><div><b>{fullName(person)}</b><span>{person.email}</span><em>{person.active?roleName[person.role]:"WYŁĄCZONE"}</em></div><aside><button onClick={()=>saveName(person)}>DANE</button>{person.email!==OWNER&&<select value={person.role} onChange={e=>changeRole(person,e.target.value as StaffRole)} aria-label={`Rola ${person.email}`}><option value="editor_in_chief">REDAKTOR NACZELNY</option><option value="deputy_editor_in_chief">ZASTĘPCA NACZELNEGO</option><option value="journalist">DZIENNIKARZ</option></select>}{person.email!==OWNER&&<button onClick={()=>toggle(person)}>{person.active?"WYŁĄCZ":"WŁĄCZ"}</button>}</aside></article>)}</div></div></section></main>;
}
