"use client";

import { FormEvent, useEffect, useState } from "react";
import { getSupabase } from "../../../lib/supabase";
import { logActivity } from "../../../lib/activity-log";
import "./team.css";

type StaffRole = "editor_in_chief"|"deputy_editor_in_chief"|"journalist";
type Staff = { id:number; email:string; first_name:string|null; last_name:string|null; display_name:string|null; role:StaffRole; active:boolean; created_at:string };
const roleName:Record<StaffRole,string>={editor_in_chief:"REDAKTOR NACZELNY",deputy_editor_in_chief:"ZASTĘPCA REDAKTORA NACZELNEGO",journalist:"DZIENNIKARZ"};
const fullName=(person:{first_name?:string|null;last_name?:string|null;display_name?:string|null})=>[person.first_name,person.last_name].filter(Boolean).join(" ")||person.display_name||"CZŁONEK REDAKCJI";

export default function ZespolPage() {
  const [ok,setOk]=useState<boolean|null>(null); const [staff,setStaff]=useState<Staff[]>([]); const [currentEmail,setCurrentEmail]=useState(""); const [email,setEmail]=useState(""); const [firstName,setFirstName]=useState(""); const [lastName,setLastName]=useState(""); const [password,setPassword]=useState(""); const [accountRole,setAccountRole]=useState<StaffRole>("journalist"); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false); const client=()=>getSupabase();
  async function load(){const {data,error}=await client().from("staff_accounts").select("id,email,first_name,last_name,display_name,role,active,created_at").order("created_at",{ascending:false});if(error)setMessage("Nie udało się wczytać zespołu.");setStaff((data as Staff[]|null)??[]);}
  useEffect(()=>{client().auth.getUser().then(async ({data})=>{const email=data.user?.email?.toLowerCase()||"";const {data:person}=await client().from("staff_accounts").select("role,active").eq("email",email).maybeSingle();const allowed=Boolean(person?.active&&["editor_in_chief","deputy_editor_in_chief"].includes(person.role));setCurrentEmail(email);setOk(allowed);if(allowed)await load();});},[]);
  function isLastActiveChief(person:Staff){return person.active&&person.role==="editor_in_chief"&&staff.filter(item=>item.active&&item.role==="editor_in_chief").length<=1;}
  async function add(event:FormEvent){
    event.preventDefault(); setSaving(true); setMessage("");
    const normalized=email.trim().toLowerCase(); const display=[firstName.trim(),lastName.trim()].filter(Boolean).join(" ");
    if(password.length<10){setSaving(false);setMessage("Hasło musi mieć minimum 10 znaków.");return;}
    const {data:sessionData}=await client().auth.getSession(); const accessToken=sessionData.session?.access_token;
    if(!accessToken){setSaving(false);setMessage("Sesja wygasła. Zaloguj się ponownie.");return;}
    const response=await fetch("/api/redakcja/konta",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${accessToken}`},body:JSON.stringify({email:normalized,firstName:firstName.trim(),lastName:lastName.trim(),password,role:accountRole})});
    const result=await response.json().catch(()=>({})); setSaving(false);
    if(!response.ok){setMessage(result?.error||result?.message||"Nie udało się utworzyć konta.");return;}
    setMessage(`Utworzono konto ${normalized}: ${roleName[accountRole]}. Użytkownik może od razu się zalogować.`);
    await logActivity({actorEmail:currentEmail,action:"staff_added",entityType:"staff",entityId:normalized,entityLabel:display||normalized,details:{role:accountRole,authCreated:true}});
    setEmail("");setFirstName("");setLastName("");setPassword("");setAccountRole("journalist");await load();
  }
  async function saveName(person:Staff){const first=window.prompt("Imię:",person.first_name||"");if(first===null)return;const last=window.prompt("Nazwisko:",person.last_name||"");if(last===null)return;const display=[first.trim(),last.trim()].filter(Boolean).join(" ");const {error}=await client().from("staff_accounts").update({first_name:first.trim()||null,last_name:last.trim()||null,display_name:display||null}).eq("id",person.id);setMessage(error?"Nie udało się zapisać danych autora.":"Dane autora zapisane.");if(!error){await logActivity({actorEmail:currentEmail,action:"staff_updated",entityType:"staff",entityId:person.id,entityLabel:display||person.email});await load();}}
  async function toggle(person:Staff){if(person.active&&isLastActiveChief(person)){setMessage("Nie możesz wyłączyć ostatniego aktywnego Redaktora Naczelnego.");return;}if(person.email===currentEmail&&person.active&&!window.confirm("Wyłączasz własne konto. Po tej operacji stracisz dostęp do panelu. Kontynuować?"))return;const {error}=await client().from("staff_accounts").update({active:!person.active}).eq("id",person.id);setMessage(error?"Nie udało się zmienić stanu konta.":person.active?"Konto wyłączone.":"Konto aktywne.");if(!error){await logActivity({actorEmail:currentEmail,action:"staff_toggled",entityType:"staff",entityId:person.id,entityLabel:fullName(person),details:{active:!person.active}});await load();}}
  async function changeRole(person:Staff, role:StaffRole){if(person.role==="editor_in_chief"&&role!=="editor_in_chief"&&isLastActiveChief(person)){setMessage("Najpierw nadaj rolę Redaktora Naczelnego innej aktywnej osobie.");return;}if(!window.confirm(`Nadać ${person.email} rolę: ${roleName[role]}?`))return;const {error}=await client().from("staff_accounts").update({role}).eq("id",person.id);setMessage(error?"Nie udało się zmienić roli.":"Uprawnienia zapisane.");if(!error){await logActivity({actorEmail:currentEmail,action:"staff_role_changed",entityType:"staff",entityId:person.id,entityLabel:fullName(person),details:{role}});await load();}}
  async function sendReset(person:Staff){if(!window.confirm(`Wysłać link zmiany hasła na ${person.email}?`))return;setMessage("");const {error}=await client().auth.resetPasswordForEmail(person.email,{redirectTo:`${window.location.origin}/redakcja/haslo`});setMessage(error?"Nie udało się wysłać linku resetu.":"Link zmiany hasła został wysłany.");}
  if(ok===null)return <main className="team-page">ŁADOWANIE…</main>;if(!ok)return <main className="team-page"><h1>DOSTĘP ZAMKNIĘTY.</h1></main>;
  return <main className="team-page"><header><a href="/" className="wordmark">STREET<span>SCOPE</span></a><nav><a href="/redakcja/dashboard">DASHBOARD</a><a href="/redakcja/material">EDYTOR</a><a href="/redakcja/zarzadzaj">AKCEPTACJA</a><a href="/redakcja/rekrutacja">REKRUTACJA</a><a href="/redakcja/archiwum">ARCHIWUM</a></nav></header><section className="team-head"><p className="kicker"><i/> ZARZĄDZANIE ZESPOŁEM</p><h1>ZESPÓŁ<br/><em>REDAKCJI.</em></h1><p>Nowe konto tworzy się teraz w całości z tego panelu — profil redakcyjny i login Supabase Auth powstają jednocześnie. Nie musisz dodawać nowych użytkowników przez SQL.</p><a href="/redakcja/haslo">ZMIEŃ SWOJE HASŁO →</a></section><section className="team-grid"><form onSubmit={add}><p className="kicker"><i/> NOWE KONTO</p><label>IMIĘ<input value={firstName} onChange={e=>setFirstName(e.target.value)} placeholder="Izumi" /></label><label>NAZWISKO<input value={lastName} onChange={e=>setLastName(e.target.value)} placeholder="Daigo" /></label><label>E-MAIL PRACOWNIKA<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="redaktor@email.pl" /></label><label>HASŁO STARTOWE<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={10} autoComplete="new-password" placeholder="minimum 10 znaków" /></label><label>ROLA<select value={accountRole} onChange={e=>setAccountRole(e.target.value as StaffRole)}><option value="editor_in_chief">REDAKTOR NACZELNY — pełny dostęp</option><option value="deputy_editor_in_chief">ZASTĘPCA NACZELNEGO — pełny dostęp</option><option value="journalist">DZIENNIKARZ — pisze i wysyła</option></select></label><button className="primary" disabled={saving}>{saving?"TWORZENIE…":"UTWÓRZ KONTO →"}</button><small role="status">{message}</small></form><div><p className="kicker"><i/> KONTA REDAKCJI</p><div className="staff-list">{staff.map(person=><article key={person.id}><div><b>{fullName(person)}</b><span>{person.email}</span><em>{person.active?roleName[person.role]:"WYŁĄCZONE"}</em></div><aside><button onClick={()=>saveName(person)}>DANE</button><select value={person.role} onChange={e=>changeRole(person,e.target.value as StaffRole)} aria-label={`Rola ${person.email}`}><option value="editor_in_chief">REDAKTOR NACZELNY</option><option value="deputy_editor_in_chief">ZASTĘPCA NACZELNEGO</option><option value="journalist">DZIENNIKARZ</option></select><button onClick={()=>sendReset(person)}>RESET HASŁA</button><button onClick={()=>toggle(person)}>{person.active?"WYŁĄCZ":"WŁĄCZ"}</button></aside></article>)}</div></div></section></main>;
}
