import { HomeNewsBoard } from "./home-news-board";
import { PopularStories } from "./popular-stories";
import { StreetCultureStrip } from "./street-culture-strip";
import { HomeGuideStrip } from "./home-guide-strip";
import { ScopePicks } from "./scope-picks";
import { HomeMarketStrip } from "./home-market-strip";
import "./recruit-home.css";
import "./home-nav.css";

export default function Home() {
  const ticker = ["NEWS THAT HITS HOME.", "LA MESA · LOS SANTOS", "TOW & TRADE · AUTA NA SPRZEDAŻ", "NOWE MATERIAŁY KAŻDEGO DNIA"];
  return <main><div className="ticker" aria-label="StreetScope"><div className="ticker-label">BREAKING</div><div className="ticker-window"><div className="ticker-track">{[...ticker,...ticker].map((item,index)=><span key={`${item}-${index}`}><b>●</b>{item}</span>)}</div></div></div><header className="nav stage31-nav"><a href="/" className="wordmark">STREET<span>SCOPE</span></a><nav><a href="/wiadomosci">WIADOMOŚCI</a><a href="/fashion">FASHION</a><a href="/motor">MOTOR</a><a href="/market">TOW & TRADE</a><a href="/miasto">MIASTO</a><a href="/guide">SCOPE GUIDE</a><a href="/o-redakcji">O REDAKCJI</a><a href="/zglos-temat">ZGŁOŚ TEMAT</a><a className="nav-join-link" href="/dolacz">DOŁĄCZ DO NAS</a></nav></header><HomeNewsBoard/><PopularStories/><ScopePicks/><HomeMarketStrip/><StreetCultureStrip/><HomeGuideStrip/><section className="recruit-home-card"><div><p className="kicker"><i/> REKRUTACJA / CV</p><h2>MASZ OKO DO MIASTA?<br/><em>DOŁĄCZ DO REDAKCJI.</em></h2><p>Reporter, fotograf, motoryzacja, moda albo kultura. Wyślij zgłoszenie, podepnij portfolio i CV bezpośrednio przez StreetScope.</p></div><a href="/dolacz">WYŚLIJ CV / ZGŁOSZENIE →</a></section><section className="street-intro"><div className="street-brand"><a href="/" className="wordmark">STREET<span>SCOPE</span></a><p>NIEZALEŻNA REDAKCJA ULICZNA</p><strong>Z ULICY. DLA LUDZI. Z MIASTA.</strong></div><div className="street-copy"><p className="kicker"><i/> NEWS THAT HITS HOME.</p><h2>MIASTO NIE CZEKA.<br/><em>MY TEŻ NIE.</em></h2><p>Relacje, ludzie, lokalne konflikty, kultura, biznes i nocne życie Los Santos — z perspektywy ulicy.</p><div className="street-actions"><a href="/o-redakcji">POZNAJ REDAKCJĘ →</a><a href="/zglos-temat">ZGŁOŚ TEMAT →</a></div></div></section><section className="join-strip"><div><span>MASZ COŚ, O CZYM POWINNO WIEDZIEĆ MIASTO?</span><h2>DAJ NAM SYGNAŁ.</h2></div><a href="/zglos-temat">NAPISZ DO REDAKCJI →</a></section><footer className="stage31-footer"><div><a href="/" className="wordmark">STREET<span>SCOPE</span></a><p>© 2026 StreetScope</p></div><nav><a href="/wiadomosci">WIADOMOŚCI</a><a href="/miasto">MIASTO</a><a href="/market">TOW & TRADE</a><a href="/guide">SCOPE GUIDE</a><a href="/o-redakcji">O REDAKCJI</a><a href="/dolacz">DOŁĄCZ</a></nav><p>NEWS THAT <b>HITS</b> HOME.</p></footer></main>;
}
