"use client";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { getSupabase } from "../../../lib/supabase";
import { logActivity } from "../../../lib/activity-log";
import "./culture-editor.css";

type Kind="fashion"|"motor";
type StaffRole="editor_in_chief"|"deputy_editor_in_chief"|"journalist";
type Feature={id:number;kind:Kind;title:string;subtitle:string|null;description:string|null;image_url:string|null;gallery:string[]|null;person_name:string|null;location:string|null;vehicle_model:string|null;vehicle_year:string|null;owner_name:string|null;workshop:string|null;details:string|null;badge:string|null;featured:boolean;published:boolean;created_at:string;archived_at:string|null;created_by:string|null;review_status:string|null;review_note:string|null;submitted_by:string|null};
const blank={title:"",subtitle:"",description:"",person_name:"",location:"",vehicle_model:"",vehicle_year:"",owner_name:"",workshop:"",details:"",badge:""};

export default function CultureEditor(){
 const [allowed,setAllowed]=useState<boolean|null>(null);const [email,setEmail]=useState("");const [role,setRole]=useState<StaffRole>("journalist");const [kind,setKind]=useState<Kind>("fashion");const [form,setForm]=useState(blank);const [cover,setCover]=useState<File|null>(null);const [gallery,setGallery]=useState<File[]>([]);const [galleryPreviews,setGalleryPreviews]=useState<string[]>([]);const [existingCover,setExistingCover]=useState("");const [existingGallery,setExistingGallery]=useState<string[]>([]);const [featured,setFeatured]=useState(false);const [published,setPublished]=useState(false);const [editingId,setEditingId]=useState<number|null>(null);const [rows,setRows]=useState<Feature[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const client=()=>getSupabase(); const isApprover=["editor_in_chief","deputy_editor_in_chief"].includes(role);
 async function load(){const {data}=await client().from("street_features").select("*").is("archived_at",null).order("created_at",{ascending:false}).limit(80);setRows((data as Feature[]|null)||[])}
 useEffect(()=>{client().auth.getUser().then(async({data})=>{const e=data.user?.email?.toLowerCase()||"";setEmail(e);if(!e){setAllowed(false);return;}const {data:staff}=await client().from("staff_accounts").select("active,role").eq("email",e).maybeSingle();const ok=Boolean(staff?.active);setAllowed(ok);if(staff?.role)setRole(staff.role as StaffRole);if(ok)await load();});},[]);
 useEffect(()=>{const urls=gallery.map(file=>URL.createObjectURL(file));setGalleryPreviews(urls);return()=>urls.forEach(url=>URL.revokeObjectURL(url));},[gallery]);
 function field(name:keyof typeof blank,value:string){setForm(v=>({...v,[name]:value}))}
 function addGalleryFiles(e:ChangeEvent<HTMLInputElement>){const picked=Array.from(e.target.files||[]);if(!picked.length)return;const invalid=picked.find(file=>!file.type.startsWith("image/")||file.size>8*1024*1024);if(invalid){setMessage(`„${invalid.name}” nie jest poprawnym zdjęciem albo przekracza 8 MB.`);e.target.value="";return;}setGallery(prev=>{const merged=[...prev,...picked];if(merged.length>6)setMessage("Galeria może zawierać maksymalnie 6 nowych zdjęć. Nadmiar został pominięty.");else setMessage("");return merged.slice(0,6)});e.target.value=""}
 function removeGalleryFile(index:number){setGallery(prev=>prev.filter((_,i)=>i!==index))}
 async function upload(file:File){if(!file.type.startsWith("image/")||file.size>8*1024*1024)throw new Error("Zdjęcie musi mieć maks. 8 MB.");const ext=file.name.split(".").pop()?.replace(/[^a-z0-9]/gi,"")||"jpg";const path=`culture-${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await client().storage.from("article-images").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return client().storage.from("article-images").getPublicUrl(path).data.publicUrl}
 async function save(e:FormEvent){e.preventDefault();if(form.title.trim().length<3){setMessage("Dodaj tytuł wpisu.");return;}setBusy(true);setMessage("");try{const image_url=cover?await upload(cover):existingCover||null;const newGallery:string[]=[];for(const file of gallery.slice(0,6))newGallery.push(await upload(file));const galleryUrls=[...existingGallery,...newGallery].slice(0,8);const now=new Date().toISOString();const payload={kind,title:form.title.trim(),subtitle:form.subtitle.trim()||null,description:form.description.trim()||null,image_url,gallery:galleryUrls,person_name:kind==="fashion"?form.person_name.trim()||null:null,location:kind==="fashion"?form.location.trim()||null:null,vehicle_model:kind==="motor"?form.vehicle_model.trim()||null:null,vehicle_year:kind==="motor"?form.vehicle_year.trim()||null:null,owner_name:kind==="motor"?form.owner_name.trim()||null:null,workshop:kind==="motor"?form.workshop.trim()||null:null,details:form.details.trim()||null,badge:form.badge.trim()||null,featured:isApprover?featured:false,published:isApprover?published:false,review_status:isApprover?(published?"published":"draft"):"review",review_note:null,submitted_by:email,submitted_at:now,created_by:email,updated_at:now};const result=editingId?await client().from("street_features").update(payload).eq("id",editingId).select("id").single():await client().from("street_features").insert(payload).select("id").single();if(result.error)throw result.error;const id=Number(result.data?.id||editingId||0);await logActivity({actorEmail:email,action:editingId?"feature_updated":"feature_created",entityType:"feature",entityId:id,entityLabel:form.title,details:{kind,review_status:payload.review_status}});setMessage(isApprover?(published?"Wpis opublikowany.":"Wpis zapisany jako szkic."):"Wpis wysłany do akceptacji Naczelnego/Zastępcy.");reset();await load();}catch(err){setMessage(err instanceof Error?err.message:"Nie udało się zapisać wpisu.");}finally{setBusy(false)}}
 function reset(){setForm(blank);setCover(null);setGallery([]);setExistingCover("");setExistingGallery([]);setFeatured(false);setPublished(false);setEditingId(null)}
 function edit(row:Feature){if(!isApprover&&row.created_by!==email&&row.submitted_by!==email)return;setKind(row.kind);setEditingId(row.id);setForm({title:row.title||"",subtitle:row.subtitle||"",description:row.description||"",person_name:row.person_name||"",location:row.location||"",vehicle_model:row.vehicle_model||"",vehicle_year:row.vehicle_year||"",owner_name:row.owner_name||"",workshop:row.workshop||"",details:row.details||"",badge:row.badge||""});setExistingCover(row.image_url||"");setExistingGallery(row.gallery||[]);setFeatured(row.featured);setPublished(row.published);window.scrollTo({top:0,behavior:"smooth"})}
 async function archive(row:Feature){if(!isApprover)return;if(!confirm(`Przenieść „${row.title}” do archiwum?`))return;const {error}=await client().from("street_features").update({archived_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",row.id);if(error){setMessage(error.message);return;}await logActivity({actorEmail:email,action:"feature_archived",entityType:"feature",entityId:row.id,entityLabel:row.title,details:{kind:row.kind}});await load()}
 const visible=rows.filter(r=>r.kind===kind&&(isApprover||r.created_by===email||r.submitted_by===email));
 if(allowed===null)return <main className="culture-editor">ŁADOWANIE…</main>;if(!allowed)return <main className="culture-editor"><h1>DOSTĘP ZAMKNIĘTY.</h1></main>;
 return <main className="culture-editor"><header><a href="/redakcja" className="wordmark">STREET<span>SCOPE</span></a><nav><a href="/redakcja/dashboard">DASHBOARD</a><a href="/redakcja/material">MATERIAŁ</a><a href="/fashion" target="_blank">FASHION ↗</a><a href="/motor" target="_blank">MOTOR ↗</a></nav></header>
 <section className="ce-head"><p>STREET CULTURE / CMS</p><h1>FASHION<br/><em>& MOTOR.</em></h1><span>{isApprover?"Możesz zapisywać szkice lub publikować.":"LOOK i BUILD trafiają do akceptacji przed publikacją."}</span></section>
 <div className="ce-tabs"><button className={kind==="fashion"?"active":""} onClick={()=>{setKind("fashion");reset()}}>FASHION</button><button className={kind==="motor"?"active":""} onClick={()=>{setKind("motor");reset()}}>MOTOR</button></div>
 <section className="ce-layout"><form onSubmit={save} className="ce-form"><div className="ce-form-title"><b>{editingId?"EDYTUJ":"DODAJ"} {kind==="fashion"?"LOOK":"BUILD"}</b>{editingId&&<button type="button" onClick={reset}>ANULUJ EDYCJĘ</button>}</div>
 <label>TYTUŁ<input value={form.title} onChange={e=>field("title",e.target.value)} placeholder={kind==="fashion"?"LOOK #024 — NIGHT SHIFT":"BUILD #017 — SULTAN RS"}/></label><label>ZAJAWKA<input value={form.subtitle} onChange={e=>field("subtitle",e.target.value)} placeholder="Jedno zdanie na kartę i hero"/></label>
 {kind==="fashion"?<div className="ce-row"><label>OSOBA / KSYWA<input value={form.person_name} onChange={e=>field("person_name",e.target.value)} placeholder="Doppy"/></label><label>LOKALIZACJA<input value={form.location} onChange={e=>field("location",e.target.value)} placeholder="La Mesa"/></label></div>:<><div className="ce-row"><label>MODEL AUTA<input value={form.vehicle_model} onChange={e=>field("vehicle_model",e.target.value)} placeholder="Sultan RS"/></label><label>ROK<input value={form.vehicle_year} onChange={e=>field("vehicle_year",e.target.value)} placeholder="2001"/></label></div><div className="ce-row"><label>WŁAŚCICIEL<input value={form.owner_name} onChange={e=>field("owner_name",e.target.value)} placeholder="Doppy"/></label><label>WARSZTAT<input value={form.workshop} onChange={e=>field("workshop",e.target.value)} placeholder="Nazwa warsztatu"/></label></div></>}
 <label>{kind==="fashion"?"ELEMENTY OUTFITU / MARKI":"MODYFIKACJE / SPEC"}<textarea value={form.details} onChange={e=>field("details",e.target.value)} placeholder={kind==="fashion"?"Kurtka — ...\nSpodnie — ...\nButy — ...":"Felgi — ...\nZawieszenie — ...\nSilnik — ..."}/></label><label>OPIS / HISTORIA<textarea value={form.description} onChange={e=>field("description",e.target.value)} placeholder="Krótka historia osoby, outfitu albo buildu..."/></label>
 <div className="ce-row"><label>STEMPEL / BADGE<input value={form.badge} onChange={e=>field("badge",e.target.value)} placeholder={kind==="fashion"?"FIT OF THE WEEK":"CAR OF THE WEEK"}/></label><label>OKŁADKA<input type="file" accept="image/*" onChange={(e:ChangeEvent<HTMLInputElement>)=>setCover(e.target.files?.[0]||null)}/></label></div>
 <label className="ce-gallery-picker">GALERIA — DO 6 NOWYCH ZDJĘĆ<input type="file" accept="image/*" multiple onChange={addGalleryFiles}/><small>Możesz zaznaczyć kilka zdjęć naraz albo wybierać je partiami. Łącznie maks. 6 nowych zdjęć.</small></label>
 {gallery.length>0&&<div className="ce-gallery-preview">{gallery.map((file,index)=><div className="ce-gallery-item" key={`${file.name}-${file.lastModified}-${index}`}><img src={galleryPreviews[index]||""} alt=""/><span title={file.name}>{index+1}. {file.name}</span><button type="button" onClick={()=>removeGalleryFile(index)}>USUŃ</button></div>)}</div>}
 {(existingCover||existingGallery.length>0)&&<div className="ce-existing">{existingCover&&<img src={existingCover} alt=""/>}<span>{existingGallery.length} zdjęć już w galerii</span></div>}
 {isApprover?<div className="ce-checks"><label><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/> WYRÓŻNIONY</label><label><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/> PUBLICZNY</label></div>:<p className="ce-message">PUBLIKACJA: PO AKCEPTACJI NACZELNEGO / ZASTĘPCY</p>}
 <button className="ce-submit" disabled={busy}>{busy?"ZAPISUJĘ…":editingId?(isApprover?"ZAPISZ ZMIANY →":"WYŚLIJ PONOWNIE DO AKCEPTACJI →"):(isApprover?"ZAPISZ WPIS →":"WYŚLIJ DO AKCEPTACJI →")}</button>{message&&<p className="ce-message">{message}</p>}</form>
 <aside className="ce-list"><div><b>{kind==="fashion"?"FASHION":"MOTOR"}</b><span>{visible.length} WPISÓW</span></div>{visible.length?visible.map(row=><article key={row.id}>{row.image_url&&<img src={row.image_url} alt=""/>}<section><small>{row.featured?"★ FEATURED · ":""}{(row.review_status|| (row.published?"published":"draft")).toUpperCase()} · {new Date(row.created_at).toLocaleDateString("pl-PL")}</small><h3>{row.title}</h3><p>{row.review_note?`UWAGA: ${row.review_note}`:(row.subtitle||row.person_name||row.vehicle_model||"StreetScope")}</p><div><button onClick={()=>edit(row)}>EDYTUJ</button>{row.published&&<a href={`/${row.kind}/${row.id}`} target="_blank">PODGLĄD ↗</a>}{isApprover&&<button onClick={()=>archive(row)}>ARCHIWIZUJ</button>}</div></section></article>):<p>Brak wpisów w tym dziale.</p>}</aside></section></main>
}
