"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabase } from "../../../lib/supabase";
import "./logs.css";

type LogRow={id:number;actor_email:string;action:string;entity_type:string;entity_id:string|null;entity_label:string|null;details:Record<string,unknown>|null;created_at:string};
const labels:Record<string,string>={article_created:"UTWORZONO MATERIAŁ",article_updated:"ZAKTUALIZOWANO MATERIAŁ",article_submitted:"WYSŁANO DO AKCEPTACJI",article_published:"OPUBLIKOWANO MATERIAŁ", article_scheduled:"ZAPLANOWANO PUBLIKACJĘ",article_archived:"ZARCHIWIZOWANO MATERIAŁ",article_restored:"PRZYWRÓCONO MATERIAŁ",article_deleted:"USUNIĘTO MATERIAŁ TRWALE",article_changes_requested:"ODESŁANO DO POPRAWY",tip_status_changed:"ZMIENIONO STATUS ZGŁOSZENIA",tip_archived:"ZARCHIWIZOWANO ZGŁOSZENIE",tip_restored:"PRZYWRÓCONO ZGŁOSZENIE",tip_deleted:"USUNIĘTO ZGŁOSZENIE TRWALE",recruitment_status_changed:"ZMIENIONO STATUS REKRUTACJI",staff_added:"DODANO KONTO",staff_updated:"ZMIENIONO DANE KONTA",staff_role_changed:"ZMIENIONO ROLĘ",staff_toggled:"ZMIENIONO DOSTĘP",feature_created:"DODANO STREET CULTURE",feature_updated:"ZAKTUALIZOWANO STREET CULTURE",feature_archived:"ZARCHIWIZOWANO STREET CULTURE"};
export default function LogsPage(){
 const [allowed,setAllowed]=useState<boolean|null>(null);const [rows,setRows]=useState<LogRow[]>([]);const [query,setQuery]=useState("");const [kind,setKind]=useState("all");const [message,setMessage]=useState("");const client=()=>getSupabase();
 async function load(){const {data,error}=await client().from("activity_logs").select("id,actor_email,action,entity_type,entity_id,entity_label,details,created_at").order("created_at",{ascending:false}).limit(300);if(error)setMessage(error.message);setRows((data as LogRow[]|null)??[]);}
 useEffect(()=>{client().auth.getUser().then(async({data})=>{const email=data.user?.email?.toLowerCase()||"";const {data:person}=await client().from("staff_accounts").select("active,role").eq("email",email).maybeSingle();const ok=Boolean(person?.active&&["editor_in_chief","deputy_editor_in_chief"].includes(person.role));setAllowed(ok);if(ok)await load();});},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(r=>(kind==="all"||r.entity_type===kind)&&(!q||[r.actor_email,r.action,r.entity_type,r.entity_label||"",r.entity_id||""].some(v=>v.toLowerCase().includes(q))));},[rows,query,kind]);
 if(allowed===null)return <main className="logs-page">ŁADOWANIE…</main>;if(!allowed)return <main className="logs-page"><h1>DOSTĘP ZAMKNIĘTY.</h1></main>;
 return <main className="logs-page"><header><a href="/" className="wordmark">STREET<span>SCOPE</span></a><nav><a href="/redakcja/dashboard">DASHBOARD</a><a href="/redakcja/zarzadzaj">ZARZĄDZAJ</a><a href="/redakcja/archiwum">ARCHIWUM</a></nav></header><section className="logs-head"><p className="kicker"><i/> AUDYT REDAKCJI</p><h1>DZIENNIK<br/><em>DZIAŁAŃ.</em></h1><p>{message||"Kto, co i kiedy zrobił w panelu StreetScope."}</p><div className="logs-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="SZUKAJ: OSOBA, AKCJA, MATERIAŁ…"/><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">WSZYSTKO</option><option value="article">MATERIAŁY</option><option value="tip">ZGŁOSZENIA</option><option value="recruitment">REKRUTACJA</option><option value="staff">ZESPÓŁ</option><option value="feature">FASHION / MOTOR</option></select><span>{filtered.length}</span></div></section><section className="logs-list">{filtered.length?filtered.map(row=><article key={row.id}><time>{new Date(row.created_at).toLocaleString("pl-PL")}</time><div><span>{labels[row.action]||row.action}</span><h2>{row.entity_label||`${row.entity_type} #${row.entity_id||"—"}`}</h2><small>{row.actor_email}</small></div></article>):<p>Brak wpisów pasujących do filtrów.</p>}</section></main>;
}
