"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabase } from "../../../lib/supabase";
import "./recruitment.css";

type Status = "new"|"contacted"|"rejected"|"accepted";
type Application = { id:number; first_name:string; last_name:string; phone:string; email:string; message:string; portfolio_url:string|null; cv_path:string|null; status:Status; created_at:string };
const labels:Record<Status,string> = { new:"NOWE", contacted:"KONTAKT", rejected:"ODRZUCONE", accepted:"PRZYJĘTE" };

export default function RecruitmentPanel() {
  const [allowed,setAllowed]=useState<boolean|null>(null); const [rows,setRows]=useState<Application[]>([]); const [message,setMessage]=useState(""); const [query,setQuery]=useState(""); const [status,setStatusFilter]=useState<"all"|Status>("all"); const [cvLinks,setCvLinks]=useState<Record<number,string>>({});
  const client=()=>getSupabase();
  async function load(){const {data,error}=await client().from("recruitment_applications").select("id,first_name,last_name,phone,email,message,portfolio_url,cv_path,status,created_at").order("created_at",{ascending:false});if(error)setMessage(error.message);setRows((data as Application[]|null)??[]);}
  useEffect(()=>{client().auth.getUser().then(async({data})=>{const email=data.user?.email?.toLowerCase()||"";const {data:person}=await client().from("staff_accounts").select("active,role").eq("email",email).maybeSingle();const ok=Boolean(person?.active&&["editor_in_chief","deputy_editor_in_chief"].includes(person.role));setAllowed(ok);if(ok)await load();});},[]);
  async function changeStatus(id:number,next:Status){const {error}=await client().from("recruitment_applications").update({status:next,updated_at:new Date().toISOString()}).eq("id",id);setMessage(error?error.message:"Status zgłoszenia zapisany.");if(!error)await load();}
  async function openCv(row:Application){if(!row.cv_path)return;const cached=cvLinks[row.id];if(cached){window.open(cached,"_blank","noopener,noreferrer");return;}const {data,error}=await client().storage.from("recruitment-cv").createSignedUrl(row.cv_path,60*10);if(error||!data?.signedUrl){setMessage(error?.message||"Nie udało się otworzyć CV.");return;}setCvLinks(current=>({...current,[row.id]:data.signedUrl}));window.open(data.signedUrl,"_blank","noopener,noreferrer");}
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return rows.filter(row=>{if(status!=="all"&&row.status!==status)return false;if(!needle)return true;return [row.first_name,row.last_name,row.phone,row.email,row.message,row.portfolio_url||""].some(value=>value.toLowerCase().includes(needle));});},[rows,query,status]);
  if(allowed===null)return <main className="recruitment-panel">ŁADOWANIE…</main>;
  if(!allowed)return <main className="recruitment-panel"><h1>DOSTĘP<br/><em>ZAMKNIĘTY.</em></h1></main>;
  return <main className="recruitment-panel"><header><a className="wordmark" href="/">STREET<span>SCOPE</span></a><nav><a href="/redakcja/material">EDYTOR</a><a href="/redakcja/zarzadzaj">ZGŁOSZENIA</a><a href="/redakcja/archiwum">ARCHIWUM</a><a href="/redakcja/zespol">ZESPÓŁ</a></nav></header><section className="recruitment-panel-head"><p className="kicker"><i/> NABÓR DO REDAKCJI</p><h1>ZGŁOSZENIA<br/><em>REKRUTACYJNE.</em></h1><p>{message||"Przeglądaj kandydatury, filtruj zgłoszenia i oznaczaj etap kontaktu."}</p><div className="recruitment-tools"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="SZUKAJ: IMIĘ, E-MAIL, TELEFON, TREŚĆ…"/><select value={status} onChange={event=>setStatusFilter(event.target.value as "all"|Status)}><option value="all">WSZYSTKIE STATUSY</option><option value="new">NOWE</option><option value="contacted">KONTAKT</option><option value="accepted">PRZYJĘTE</option><option value="rejected">ODRZUCONE</option></select><span>{filtered.length} / {rows.length}</span></div></section><section className="application-list">{filtered.length?filtered.map(row=><article key={row.id}><aside><span className={`application-status status-${row.status}`}>{labels[row.status]}</span><b>{new Date(row.created_at).toLocaleDateString("pl-PL",{day:"2-digit",month:"long",year:"numeric"})}</b></aside><div><h2>{row.first_name} {row.last_name}</h2><p className="application-contact"><a href={`mailto:${row.email}`}>{row.email}</a><a href={`tel:${row.phone}`}>{row.phone}</a></p><div className="application-assets">{row.portfolio_url&&<a href={row.portfolio_url} target="_blank" rel="noreferrer">PORTFOLIO ↗</a>}{row.cv_path&&<button type="button" onClick={()=>openCv(row)}>OTWÓRZ CV ↗</button>}</div><p className="application-message">{row.message}</p><footer><button onClick={()=>changeStatus(row.id,"contacted")}>OZNACZ: KONTAKT</button><button onClick={()=>changeStatus(row.id,"accepted")}>PRZYJMIJ</button><button className="reject" onClick={()=>changeStatus(row.id,"rejected")}>ODRZUĆ</button></footer></div></article>):<p className="empty">Brak zgłoszeń pasujących do filtrów.</p>}</section></main>;
}
