alter table public.street_features add column if not exists views bigint not null default 0;
alter table public.guide_places add column if not exists views bigint not null default 0;

create table if not exists public.content_revisions (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('article','feature','guide_place')),
  entity_id bigint not null,
  actor_email text,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists content_revisions_entity_idx on public.content_revisions(entity_type,entity_id,created_at desc);
alter table public.content_revisions enable row level security;

drop policy if exists "staff read revisions" on public.content_revisions;
create policy "staff read revisions" on public.content_revisions for select to authenticated using (
  exists(select 1 from public.staff_accounts s where lower(s.email)=lower(auth.jwt()->>'email') and s.active=true)
);
drop policy if exists "staff insert revisions" on public.content_revisions;
create policy "staff insert revisions" on public.content_revisions for insert to authenticated with check (
  exists(select 1 from public.staff_accounts s where lower(s.email)=lower(auth.jwt()->>'email') and s.active=true)
);

create or replace function public.increment_feature_views(feature_id bigint)
returns void language sql security definer set search_path=public as $$
  update public.street_features set views=coalesce(views,0)+1 where id=feature_id and published=true and archived_at is null;
$$;
create or replace function public.increment_guide_views(place_id bigint)
returns void language sql security definer set search_path=public as $$
  update public.guide_places set views=coalesce(views,0)+1 where id=place_id and active=true and archived_at is null;
$$;
grant execute on function public.increment_feature_views(bigint) to anon, authenticated;
grant execute on function public.increment_guide_views(bigint) to anon, authenticated;