create table if not exists public.guide_places (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('food','nightlife','motor','shopping','services','entertainment')),
  neighborhood text,
  short_description text,
  description text,
  image_url text,
  address text,
  phone text,
  hours text,
  website_url text,
  price_level text,
  featured boolean not null default false,
  featured_home boolean not null default false,
  featured_label text default 'PROMOWANE',
  featured_order integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists guide_places_public_idx on public.guide_places(active, featured_home, featured_order);

alter table public.guide_places enable row level security;

drop policy if exists "guide public read" on public.guide_places;
create policy "guide public read" on public.guide_places for select using (active = true or auth.uid() is not null);

drop policy if exists "guide chief insert" on public.guide_places;
create policy "guide chief insert" on public.guide_places for insert to authenticated with check (
  exists(select 1 from public.staff_accounts s where lower(s.email)=lower(auth.jwt()->>'email') and s.active=true and s.role in ('editor_in_chief','deputy_editor_in_chief'))
);

drop policy if exists "guide chief update" on public.guide_places;
create policy "guide chief update" on public.guide_places for update to authenticated using (
  exists(select 1 from public.staff_accounts s where lower(s.email)=lower(auth.jwt()->>'email') and s.active=true and s.role in ('editor_in_chief','deputy_editor_in_chief'))
) with check (
  exists(select 1 from public.staff_accounts s where lower(s.email)=lower(auth.jwt()->>'email') and s.active=true and s.role in ('editor_in_chief','deputy_editor_in_chief'))
);

drop policy if exists "guide chief delete" on public.guide_places;
create policy "guide chief delete" on public.guide_places for delete to authenticated using (
  exists(select 1 from public.staff_accounts s where lower(s.email)=lower(auth.jwt()->>'email') and s.active=true and s.role in ('editor_in_chief','deputy_editor_in_chief'))
);
