"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { getSupabase } from "../../../lib/supabase";
import { logActivity } from "../../../lib/activity-log";
import { compressImageForUpload } from "../../../lib/image-optimization";
import "./guide-admin.css";

type StaffRole="editor_in_chief"|"deputy_editor_in_chief"|"journalist";
type Place = { id:number; name:string; category:string; neighborhood:string|null; short_description:string|null; description:string|null; image_url:string|null; gallery:string[]|null; address:string|null; phone:string|null; hours:string|null; website_url:string|null; price_level:string|null; featured:boolean; featured_home:boolean; featured_label:string|null; featured_order:number; active:boolean; review_status:string|null; review_note:string|null; submitted_by:string|null; archived_at:string|null; archived_by:string|null };
const empty={name:"",category:"food",neighborhood:"",short_description:"",description:"",address:"",phone:"",hours:"",website_url:"",price_level:"$",featured:false,featured_home:false,featured_label:"PROMOWANE",featured_order:100,active:false};

export default function GuideAdminPage(){
 const [allowed,setAllowed]=useState<boolean|null>(null); const [role,setRole]=useState<StaffRole>("journalist"); const [email,setEmail]=useState(""); const [rows,setRows]=useState<Place[]>([]); const [form,setForm]=useState<any>(empty); const [editing,setEditing]=useState<number|null>(null); const [query,setQuery]=useState(""); const [message,setMessage]=useState("");
 const [cover,setCover]=useState<File|null>(null); const [coverPreview,setCoverPreview]=useState(""); const [existingCover,setExistingCover]=useState(""); const [gallery,setGallery]=useState<File[]>([]); const [galleryPreviews,setGalleryPreviews]=useState<string[]>([]); const [existingGallery,setExistingGallery]=useState<string[]>([]); const [busy,setBusy]=useState(false);
 const client=()=>getSupabase(); const isApprover=["editor_in_chief","deputy_editor_in_chief"].includes(role);
 const load=async()=>{let q=client().from("guide_places").select("*").is("archived_at",null).order("featured_home",{ascending:false}).order("featured_order").order("name"); if(!isApprover&&email)q=q.eq("submitted_by",email); const {data,error}=await q; if(error)setMessage(error.message); else setRows((data as Place[]|null)??[])};
 useEffect(()=>{(async()=>{const {data}=await client().auth.getUser(); const e=data.user?.email?.toLowerCase()||""; setEmail(e); const {data:person}=await client().from("staff_accounts").select("role,active").eq("email",e).maybeSingle(); const ok=Boolean(person?.active); if(person?.role)setRole(person.role as StaffRole); setAllowed(ok); if(ok){let q=client().from("guide_places").select("*").is("archived_at",null).order("featured_home",{ascending:false}).order("featured_order").order("name"); if(!["editor_in_chief","deputy_editor_in_chief"].includes(String(person?.role)))q=q.eq("submitted_by",e); const {data:places,error}=await q; if(error)setMessage(error.message); else setRows((places as Place[]|null)??[]);}})();},[]);
 useEffect(()=>{if(!rows.length)return;const id=Number(new URLSearchParams(window.location.search).get("id")||0);if(!id)return;const r=rows.find(item=>item.id===id);if(!r)return;setEditing(r.id);setForm({...r,neighborhood:r.neighborhood||"",short_description:r.short_description||"",description:r.description||"",address:r.address||"",phone:r.phone||"",hours:r.hours||"",website_url:r.website_url||"",price_level:r.price_level||"",featured_label:r.featured_label||""});setExistingCover(r.image_url||"");setExistingGallery(r.gallery||[]);},[rows]);
 useEffect(()=>{if(!cover){setCoverPreview("");return;}const url=URL.createObjectURL(cover);setCoverPreview(url);return()=>URL.revokeObjectURL(url)},[cover]);
 useEffect(()=>{const urls=gallery.map(file=>URL.createObjectURL(file));setGalleryPreviews(urls);return()=>urls.forEach(url=>URL.revokeObjectURL(url));},[gallery]);
 const filtered=useMemo(()=>rows.filter(r=>!query||`${r.name} ${r.category} ${r.neighborhood||""}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const reset=()=>{setEditing(null);setForm(empty);setCover(null);setExistingCover("");setGallery([]);setExistingGallery([]);window.history.replaceState(null,"","/redakcja/guide")};
 const validateImage=(file:File)=>file.type.startsWith("image/")&&file.size<=8*1024*1024;
 const upload=async(file:File)=>{if(!validateImage(file))throw new Error("Zdjęcie musi być plikiem graficznym i mieć maks. 8 MB.");const optimized=await compressImageForUpload(file);const path=`guide-${Date.now()}-${crypto.randomUUID()}.webp`;const {error}=await client().storage.from("article-images").upload(path,optimized,{contentType:optimized.type,upsert:false});if(error)throw error;return client().storage.from("article-images").getPublicUrl(path).data.publicUrl};
 const onCover=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0]||null;if(file&&!validateImage(file)){setMessage("Okładka musi być zdjęciem do 8 MB.");e.target.value="";return;}setCover(file);setMessage("")};
 const addGalleryFiles=(e:ChangeEvent<HTMLInputElement>)=>{const picked=Array.from(e.target.files||[]);if(!picked.length)return;const invalid=picked.find(file=>!validateImage(file));if(invalid){setMessage(`„${invalid.name}” nie jest poprawnym zdjęciem albo przekracza 8 MB.`);e.target.value="";return;}setGallery(prev=>{const free=Math.max(0,8-existingGallery.length);const merged=[...prev,...picked];if(merged.length>free)setMessage(`Galeria może mieć maksymalnie 8 zdjęć. Możesz dodać jeszcze ${free} nowych.`);else setMessage("");return merged.slice(0,free)});e.target.value=""};
 const save=async(e:FormEvent)=>{e.preventDefault();setMessage("");setBusy(true);try{const original=rows.find(r=>r.id===editing); const now=new Date().toISOString();const image_url=cover?await upload(cover):existingCover||null;const newGallery:string[]=[];for(const file of gallery)newGallery.push(await upload(file));const galleryUrls=[...existingGallery,...newGallery].slice(0,8); const payload={name:form.name,category:form.category,neighborhood:form.neighborhood||null,short_description:form.short_description||null,description:form.description||null,image_url,gallery:galleryUrls,address:form.address||null,phone:form.phone||null,hours:form.hours||null,website_url:form.website_url||null,price_level:form.price_level||null,featured_order:Number(form.featured_order)||100,active:isApprover?Boolean(form.active):false,featured:Boolean(form.featured),featured_home:Boolean(form.featured_home),featured_label:form.featured_label||"PROMOWANE",review_status:isApprover?(form.active?"published":"draft"):"review",review_note:null,submitted_by:original?.submitted_by||email,submitted_at:now,updated_at:now}; const res=editing?await client().from("guide_places").update(payload).eq("id",editing):await client().from("guide_places").insert(payload); if(res.error)throw res.error; setMessage(isApprover?(editing?"ZAPISANO ZMIANY.":"DODANO MIEJSCE."):"Wpis wysłany do akceptacji Naczelnego/Zastępcy.");reset();await load();}catch(err){setMessage(err instanceof Error?err.message:"Nie udało się zapisać wpisu.");}finally{setBusy(false)}};
 const edit=(r:Place)=>{if(!isApprover&&r.submitted_by!==email)return;setEditing(r.id);setForm({...r,neighborhood:r.neighborhood||"",short_description:r.short_description||"",description:r.description||"",address:r.address||"",phone:r.phone||"",hours:r.hours||"",website_url:r.website_url||"",price_level:r.price_level||"",featured_label:r.featured_label||""});setCover(null);setGallery([]);setExistingCover(r.image_url||"");setExistingGallery(r.gallery||[]);window.history.replaceState(null,"",`/redakcja/guide?id=${r.id}`);window.scrollTo({top:0,behavior:"smooth"})};
 const toggle=async(r:Place,key:"active"|"featured"|"featured_home")=>{if(!isApprover)return;await client().from("guide_places").update({[key]:!r[key],updated_at:new Date().toISOString()}).eq("id",r.id);await load()};
 const archive=async(r:Place)=>{if(!isApprover)return;if(!confirm(`Przenieść „${r.name}” do archiwum?`))return;const now=new Date().toISOString();const {error}=await client().from("guide_places").update({active:false,archived_at:now,archived_by:email,updated_at:now}).eq("id",r.id);if(error){setMessage(error.message);return;}await logActivity({actorEmail:email,action:"guide_archived",entityType:"guide_place",entityId:r.id,entityLabel:r.name});setMessage("Wpis Scope Guide przeniesiony do archiwum.");if(editing===r.id)reset();await load()};
 if(allowed===null)return <main className="guide-admin">ŁADOWANIE…</main>; if(!allowed)return <main className="guide-admin"><h1>DOSTĘP ZAMKNIĘTY.</h1></main>;
 return <main className="guide-admin"><header><a href="/redakcja/dashboard" className="wordmark">STREET<span>SCOPE</span></a><nav><a href="/redakcja/dashboard">DASHBOARD</a><a href="/redakcja/materialy">MATERIAŁY</a><a href="/guide" target="_blank">OTWÓRZ GUIDE</a></nav></header>
 <section className="guide-admin__head"><p className="kicker"><i/> SCOPE GUIDE</p><h1>PRZEWODNIK<br/><em>& PROMO.</em></h1><p>{message||(isApprover?"Dodawaj miejsca do katalogu i wybieraj, które mają być promowane na stronie głównej.":"Przygotuj wpis. Publikacja nastąpi dopiero po akceptacji Naczelnego/Zastępcy.")}</p></section>
 <form className="guide-admin__form" onSubmit={save}><div className="full"><label>NAZWA</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label>KATEGORIA</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="food">Jedzenie</option><option value="nightlife">Nocne życie</option><option value="motor">Motoryzacja</option><option value="shopping">Zakupy</option><option value="services">Usługi</option><option value="entertainment">Rozrywka</option></select></div><div><label>DZIELNICA</label><input value={form.neighborhood} onChange={e=>setForm({...form,neighborhood:e.target.value})}/></div><div className="full"><label>KRÓTKI OPIS</label><input value={form.short_description} onChange={e=>setForm({...form,short_description:e.target.value})} maxLength={180}/></div><div className="full"><label>PEŁNY OPIS</label><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div>
 <div className="full upload-block"><label>OKŁADKA MIEJSCA</label><input type="file" accept="image/*" onChange={onCover}/><small>Wybierz normalnie plik z komputera. Maks. 8 MB.</small>{(coverPreview||existingCover)&&<div className="cover-preview"><img src={coverPreview||existingCover} alt="Podgląd okładki"/>{existingCover&&!cover&&<button type="button" onClick={()=>setExistingCover("")}>USUŃ OKŁADKĘ</button>}</div>}</div>
 <div className="full upload-block"><label>GALERIA — DO 8 ZDJĘĆ</label><input type="file" accept="image/*" multiple onChange={addGalleryFiles}/><small>Możesz zaznaczyć kilka zdjęć naraz albo dodawać je partiami.</small>{existingGallery.length>0&&<div className="gallery-grid">{existingGallery.map((url,index)=><div className="gallery-card" key={url}><img src={url} alt=""/><button type="button" onClick={()=>setExistingGallery(prev=>prev.filter((_,i)=>i!==index))}>USUŃ</button></div>)}</div>}{gallery.length>0&&<div className="gallery-grid">{gallery.map((file,index)=><div className="gallery-card" key={`${file.name}-${file.lastModified}-${index}`}><img src={galleryPreviews[index]||""} alt=""/><button type="button" onClick={()=>setGallery(prev=>prev.filter((_,i)=>i!==index))}>USUŃ</button></div>)}</div>}</div>
 <div><label>ADRES / LOKALIZACJA</label><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><div><label>TELEFON</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label>GODZINY</label><input value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})} placeholder="18:00–02:00"/></div><div><label>POZIOM CEN</label><select value={form.price_level} onChange={e=>setForm({...form,price_level:e.target.value})}><option>$</option><option>$$</option><option>$$$</option><option>$$$$</option></select></div><div className="full"><label>LINK BIZNESU / SOCIAL</label><input value={form.website_url} onChange={e=>setForm({...form,website_url:e.target.value})}/></div><div><label>ETYKIETA PROMO</label><input value={form.featured_label} onChange={e=>setForm({...form,featured_label:e.target.value})}/></div><div><label>KOLEJNOŚĆ NA GŁÓWNEJ</label><input type="number" value={form.featured_order} onChange={e=>setForm({...form,featured_order:e.target.value})}/></div><div className="checks full">{isApprover&&<label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> WIDOCZNE W GUIDE</label>}<label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> WYRÓŻNIONE W GUIDE</label><label><input type="checkbox" checked={form.featured_home} onChange={e=>setForm({...form,featured_home:e.target.checked})}/> PROMUJ NA GŁÓWNEJ</label></div><div className="full actions"><button type="submit" disabled={busy}>{busy?"WYSYŁAM ZDJĘCIA…":editing?(isApprover?"ZAPISZ ZMIANY":"WYŚLIJ PONOWNIE DO AKCEPTACJI"):(isApprover?"DODAJ DO GUIDE":"WYŚLIJ DO AKCEPTACJI")}</button>{editing&&<button type="button" className="secondary" onClick={reset}>ANULUJ</button>}</div></form>
 <section className="guide-admin__list"><div className="guide-admin__listhead"><h2>MIEJSCA <span>{rows.length}</span></h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="SZUKAJ…"/></div>{filtered.map(r=><article key={r.id}><div className="thumb" style={r.image_url?{backgroundImage:`url(${r.image_url})`}:undefined}/><div className="info"><small>{r.category}{r.neighborhood?` · ${r.neighborhood}`:""}</small><h3>{r.name}</h3><p>{r.review_note?`UWAGA: ${r.review_note}`:r.short_description}</p><div className="badges"><b>{(r.review_status||(r.active?"published":"draft")).toUpperCase()}</b>{r.active&&<b>PUBLICZNE</b>}{r.featured&&<b>FEATURED</b>}{r.featured_home&&<b>HOMEPAGE</b>}{Boolean(r.gallery?.length)&&<b>{r.gallery?.length} ZDJ.</b>}</div></div><div className="row-actions"><button onClick={()=>edit(r)}>EDYTUJ</button>{isApprover&&<><button onClick={()=>toggle(r,"featured_home")}>{r.featured_home?"USUŃ Z GŁÓWNEJ":"NA GŁÓWNĄ"}</button><button onClick={()=>toggle(r,"active")}>{r.active?"UKRYJ":"POKAŻ"}</button><button className="danger" onClick={()=>archive(r)}>ARCHIWIZUJ</button></>}</div></article>)}</section>
 </main>;
}
