"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { getSupabase } from "../../../lib/supabase";
import "./guide-admin.css";

type Place = { id:number; name:string; category:string; neighborhood:string|null; short_description:string|null; description:string|null; image_url:string|null; address:string|null; phone:string|null; hours:string|null; website_url:string|null; price_level:string|null; featured:boolean; featured_home:boolean; featured_label:string|null; featured_order:number; active:boolean };
const empty={name:"",category:"food",neighborhood:"",short_description:"",description:"",image_url:"",address:"",phone:"",hours:"",website_url:"",price_level:"$",featured:false,featured_home:false,featured_label:"PROMOWANE",featured_order:100,active:true};

export default function GuideAdminPage(){
 const [allowed,setAllowed]=useState<boolean|null>(null); const [rows,setRows]=useState<Place[]>([]); const [form,setForm]=useState<any>(empty); const [editing,setEditing]=useState<number|null>(null); const [query,setQuery]=useState(""); const [message,setMessage]=useState("");
 const client=()=>getSupabase();
 const load=async()=>{const {data,error}=await client().from("guide_places").select("*").order("featured_home",{ascending:false}).order("featured_order").order("name"); if(error)setMessage(error.message); else setRows((data as Place[]|null)??[])};
 useEffect(()=>{(async()=>{const {data}=await client().auth.getUser(); const email=data.user?.email?.toLowerCase()||""; const {data:person}=await client().from("staff_accounts").select("role,active").eq("email",email).maybeSingle(); const ok=Boolean(person?.active&&["editor_in_chief","deputy_editor_in_chief"].includes(person.role)); setAllowed(ok); if(ok)await load();})();},[]);
 const filtered=useMemo(()=>rows.filter(r=>!query||`${r.name} ${r.category} ${r.neighborhood||""}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const reset=()=>{setEditing(null);setForm(empty)};
 const save=async(e:FormEvent)=>{e.preventDefault();setMessage(""); const payload={...form,featured_order:Number(form.featured_order)||100}; const res=editing?await client().from("guide_places").update(payload).eq("id",editing):await client().from("guide_places").insert(payload); if(res.error){setMessage(res.error.message);return;} setMessage(editing?"ZAPISANO ZMIANY.":"DODANO MIEJSCE.");reset();await load();};
 const edit=(r:Place)=>{setEditing(r.id);setForm({...r,neighborhood:r.neighborhood||"",short_description:r.short_description||"",description:r.description||"",image_url:r.image_url||"",address:r.address||"",phone:r.phone||"",hours:r.hours||"",website_url:r.website_url||"",price_level:r.price_level||"",featured_label:r.featured_label||""});window.scrollTo({top:0,behavior:"smooth"})};
 const toggle=async(r:Place,key:"active"|"featured"|"featured_home")=>{await client().from("guide_places").update({[key]:!r[key]}).eq("id",r.id);await load()};
 const remove=async(r:Place)=>{if(!confirm(`Usunąć ${r.name} z Guide?`))return; const {error}=await client().from("guide_places").delete().eq("id",r.id);if(error)setMessage(error.message);else await load()};
 if(allowed===null)return <main className="guide-admin">ŁADOWANIE…</main>; if(!allowed)return <main className="guide-admin"><h1>DOSTĘP ZAMKNIĘTY.</h1></main>;
 return <main className="guide-admin"><header><a href="/redakcja/dashboard" className="wordmark">STREET<span>SCOPE</span></a><nav><a href="/redakcja/dashboard">DASHBOARD</a><a href="/guide" target="_blank">OTWÓRZ GUIDE</a></nav></header>
 <section className="guide-admin__head"><p className="kicker"><i/> SCOPE GUIDE</p><h1>PRZEWODNIK<br/><em>& PROMO.</em></h1><p>{message||"Dodawaj miejsca do katalogu i wybieraj, które mają być promowane na stronie głównej."}</p></section>
 <form className="guide-admin__form" onSubmit={save}><div className="full"><label>NAZWA</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label>KATEGORIA</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="food">Jedzenie</option><option value="nightlife">Nocne życie</option><option value="motor">Motoryzacja</option><option value="shopping">Zakupy</option><option value="services">Usługi</option><option value="entertainment">Rozrywka</option></select></div><div><label>DZIELNICA</label><input value={form.neighborhood} onChange={e=>setForm({...form,neighborhood:e.target.value})}/></div><div className="full"><label>KRÓTKI OPIS</label><input value={form.short_description} onChange={e=>setForm({...form,short_description:e.target.value})} maxLength={180}/></div><div className="full"><label>PEŁNY OPIS</label><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="full"><label>URL ZDJĘCIA</label><input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="https://..."/></div><div><label>ADRES / LOKALIZACJA</label><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><div><label>TELEFON</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label>GODZINY</label><input value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})} placeholder="18:00–02:00"/></div><div><label>POZIOM CEN</label><select value={form.price_level} onChange={e=>setForm({...form,price_level:e.target.value})}><option>$</option><option>$$</option><option>$$$</option><option>$$$$</option></select></div><div className="full"><label>LINK BIZNESU / SOCIAL</label><input value={form.website_url} onChange={e=>setForm({...form,website_url:e.target.value})}/></div><div><label>ETYKIETA PROMO</label><input value={form.featured_label} onChange={e=>setForm({...form,featured_label:e.target.value})}/></div><div><label>KOLEJNOŚĆ NA GŁÓWNEJ</label><input type="number" value={form.featured_order} onChange={e=>setForm({...form,featured_order:e.target.value})}/></div><div className="checks full"><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> WIDOCZNE W GUIDE</label><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> WYRÓŻNIONE W GUIDE</label><label><input type="checkbox" checked={form.featured_home} onChange={e=>setForm({...form,featured_home:e.target.checked})}/> PROMUJ NA GŁÓWNEJ</label></div><div className="full actions"><button type="submit">{editing?"ZAPISZ ZMIANY":"DODAJ DO GUIDE"}</button>{editing&&<button type="button" className="secondary" onClick={reset}>ANULUJ</button>}</div></form>
 <section className="guide-admin__list"><div className="guide-admin__listhead"><h2>MIEJSCA <span>{rows.length}</span></h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="SZUKAJ…"/></div>{filtered.map(r=><article key={r.id}><div className="thumb" style={r.image_url?{backgroundImage:`url(${r.image_url})`}:undefined}/><div className="info"><small>{r.category}{r.neighborhood?` · ${r.neighborhood}`:""}</small><h3>{r.name}</h3><p>{r.short_description}</p><div className="badges">{r.active&&<b>PUBLICZNE</b>}{r.featured&&<b>FEATURED</b>}{r.featured_home&&<b>HOMEPAGE</b>}</div></div><div className="row-actions"><button onClick={()=>edit(r)}>EDYTUJ</button><button onClick={()=>toggle(r,"featured_home")}>{r.featured_home?"USUŃ Z GŁÓWNEJ":"NA GŁÓWNĄ"}</button><button onClick={()=>toggle(r,"active")}>{r.active?"UKRYJ":"POKAŻ"}</button><button className="danger" onClick={()=>remove(r)}>USUŃ</button></div></article>)}</section>
 </main>;
}
